### ISSUE TITLE
Who can give me a acme.json sample ?

### ISSUE THREAD

**Issue by goodforever** [containous/traefik#1002]
I don't know how to write  acme.json. 
 Who can give me a acme.json sample ?

**Comment by bamarni** [comment]
There is no need to write it, this file should be generated automatically by traefik, cf. https://docs.traefik.io/toml/#acme-lets-encrypt-configuration.

You just need to set up the appropriate configuration, either manually listing your domains under `acme.domains`, or using `onHostRule` so that they're grabbed directly from your frontend rules.

**Comment by GCSBOSS** [comment]
I have lost my acme.json backup and reached Let's Encrypt weekly limit. I still have my private key and certificate pem. Can someone post an acme.json sample so that I can fill in the blanks? Thanks!

**Comment by ldez** [comment]
```json
{
  "Account": {
    "Email": "your@emmail.com",
    "Registration": {
      "body": {
        "status": "valid",
        "contact": [
          "mailto:your@emmail.com"
        ]
      },
      "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/XXXX"
    },
    "PrivateKey": "xxxx",
    "KeyType": "2048"
  },
  "Certificates": [
    {
      "Domain": {
        "Main": "domain.com",
        "SANs": ["san.domain.com"]
      },
      "Certificate": "xxx",
      "Key": "xxx"
    }
  ],
  "HTTPChallenges": null,
  "TLSChallenges": {}
}
```

**Comment by GCSBOSS** [comment]
Thank you @Idez ! Would you know the format of the `"Certificate"` field? It's not regular PEM since line breaks don't seem to be allowed.
