### ISSUE TITLE
ACME file format description

### ISSUE THREAD

**Issue by Vad1mo** [containous/traefik#1012]
### What version of Traefik are you using (`traefik version`)?

1.1.2

### What is your environment & configuration (arguments, toml...)?

I need to get the private key to sign a token in a downstream service. I need to get the private key in the .pem format or convert it into this format. 

What is the format of the acme.json private keys?
Why are there 2 private keys?
Is there a way to get a key in the pem format?

**Comment by Vad1mo** [comment]
I am still trying to figure out the format of the private key. I need to use the key in another service to encrypt the token. 

Does maybe traefik offer an option store the keys as files in pem format?

**Comment by farodin91** [comment]
I would like traefik automatic generate pem files after updating acme.json.

What is the format of the acme.json private keys?
All keys are base64 encode, after encoding the keys are in default pem format.
Why are there 2 private keys?
Their are two types of private keys.
 * One for your account at letsencrypt based on your email address
 * One for each domain.
Is there a way to get a key in the pem format?
See my first answer.
```sh
cat acme/acme.json | head -n 62 | tail -n 1 | cut -d ":" -f 2 | cut -d "\"" -f 2 | base64 --decode > certs/private.pem
cat acme/acme.json | head -n 63 | tail -n 1 | cut -d ":" -f 2 | cut -d "\"" -f 2 | base64 --decode > certs/certificate.pem
```

**Comment by brianredbeard** [comment]
To make this a more stable process, I just submitted a PR for a script to `/contrib`:

[#1484 - contrib: Dump keys/certs from acme.json to files](https://github.com/containous/traefik/pull/1484)

**Comment by kachkaev** [comment]
I'm also wondering how to get a folder with Let’s Encrypt certs so that the they could be reused inside the services (gitlab and docker-mailserver in particular). These services are declared with `docker-compose.yml`, which has something like this:

```bash
services:
  gitlab:
    #...
    volumes:
      #...
      - 'certs:/etc/gitlab/ssl'

volumes:
  certs:
    external:
      name: acme_certs
```

In my current setup, a global docker volume called `acme_certs` corresponds to a folder that [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) with [`docker-letsencrypt-nginx-proxy-companion`](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) have provided; it contains a bunch of files and subfolders for all verified Let’s Encrypt domain names.

@brianredbeard is your PR generating such a folder? If yes, how can I tell traefik to always keep it up-to-date so that I could use it as a volume for my other dockerized services?

**Comment by flesser** [comment]
@kachkaev See https://github.com/containous/traefik/issues/2418#issuecomment-369225856 for a (hacky) solution to create such volume from acme.json

**Comment by tompson** [comment]
Is there a way to to the opposite? I want to migrate from nginx to traefik and I want to import the existing PEM files from Letsencrypt into the acme.json file
