### ISSUE TITLE
Allow Kubernetes CRD Token to be specified as a file

### ISSUE THREAD

**Issue by Enquier** [containous/traefik#10144]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am working some different scenarios for using the external Kubernetes provider. I'd like to be able to specify the token as a file so I can mount it in non-kubernetes environments. For example if I want to specify the token from a secret.

**Comment by Enquier** [comment]
My current work around is to use a docker config mount a different entry point to grab the secret and append to the commands.

**Comment by nmengin** [comment]
Hello @Enquier,

Thanks for the suggestion, we think it makes a lot of sense.

If you or another community member would like to build it, let us know and we will work with you to make sure you have all the information needed so that it can be merged.  

Don’t forget to check out the [contributor docs](https://github.com/traefik/contributors-guide/blob/master/pr_guidelines) and link the PR to this issue.

**Comment by sssash18** [comment]
@nmengin I would like to work for this issue
