### ISSUE TITLE
Not taking account of `icc=false` DOCKER_OPTS

### ISSUE THREAD

**Issue by ViBiOh** [containous/traefik#103]
When using Docker provider with Traefik's Docker, if Docker is launched with `icc=false` [option](http://docs.docker.com/v1.7/articles/networking/#communication-between-containers) (according to 2.2 of https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf), the IP of backend in not reachable from Traefik.

Docker can be launched with `--ip` that defined public IP of exposed ports and can be used as a backend IP.

e.g. Docker provider automatically map `docker_name.domain` to `172.17.0.xxx`, which is not reachable from Traefik's Docker.

`172.xxx` is the `IPAddress` of `docker inspect -> NetWorkSettings`. But in `Ports` there also the exposed IP on each port.

**Comment by vdemeester** [comment]
@ViBiOh Thanks for the report :wink: Didn't really though of `icc=false` daemon so yeah, our implementation is missing some stuff. Will work on that :wink:

**Comment by dtomcej** [comment]
@vdemeester is this still an issue? or can we close this ticket?

Thanks!

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
