### ISSUE TITLE
Custom Middlewares?

### ISSUE THREAD

**Issue by ammaskartik** [containous/traefik#1048]
Apologize if this is the wrong forum, Is there support for or would be a good feature to support custom injectable middlewares. Traefik looks amazing, we are using Fabio from ebay now and are looking at mantl and found Traefik.

**Comment by ruprict** [comment]
+1

BTW, [Vulcand Proxy](https://github.com/vulcand/vulcand)  does a pretty good job with middleware if you were looking for example implementation.

**Comment by timoreimann** [comment]
#1236 might be somewhat related, at least implementation-wise.

**Comment by ruprict** [comment]
If I'm reading it right, #1236 is only about adding headers. Vulcand's approach has allowed us to write CORS and JWT middlewares that can take actions based on whatever we like. I've created middleware to translate a JSON request into SOAP and back again so we could front an old service with a new interface without having to rewrite it (maybe that's a bit too much for a proxy middleware, but the point is I can do it) 

I really like Vulcand (can you tell?) but worry about it staying maintained, which is why I'd love it if Traefik had a similar offering.

**Comment by timoreimann** [comment]
You're right, that PR is primarily about headers. The reason why I mentioned it is that I think @dtomcej has already spent a fair amount of timing digging into Traefik's middleware wiring, so hopefully the findings can prove helpful in implementing a more generic approach (i.e., not restricted to headers), in addition to getting inspired by vulcand.

Happy to see someone flesh out this issue with more details on how the feature should ideally work from a user perspective.

**Comment by gianarb** [comment]
Hello! I would like to know if there is a guideline or something related "How to extend traefik". we are thinking about extending it but we are wondering about how to keep the eventual fork up to speed and so on.

There is something around about that?

**Comment by emilevauge** [comment]
Closing this one in favor of #1336
