### ISSUE TITLE
Feature request: HTTP backend

### ISSUE THREAD

**Issue by sheerun** [containous/traefik#1053]
Hey,

This feature is called [Service Discovery](https://tyk.io/docs/tyk-api-gateway-v-2-0/api-management/service-discovery/) in [Tyk](https://tyk.io). The basic idea is that there's external API I can setup that Traefik uses to "resolve" API endpoints. For example I could setup an application and store all routes in database, then expose an endpoint that would return these routes, so Traefik can query and use them to route incoming requests. The flow is as follows:

1. Incoming request arrives to Traefik for some domain/port/path(optionally)
2. Traefik asks HTTP backend to resolve incoming query
3. Traefik uses received information to properly route incoming request
4. Next incoming request arrives for the same domain/port/path(optionally)
5. Traefik uses cached information in 2. to properly route this request
6. Traefik purges cache after 10+ seconds and will query HTTP backend next time such request arrives

What do you think?

**Comment by joonas-fi** [comment]
At beginning of request handling if Traefik were to ask an external service for anything (routing rules that you speak of), it would:

- Increase latency drastically (even with caching). Traefik is fast because all the rules are in RAM (even though they are refreshed in the background).
- Go against the entire design of Traefik (`entrypoint -> frontend (rules) -> backend pool -> backend`).

What you are describing (Tyk provides routing rules) would be better implemented as a service discovery backend. I haven't heard of Tyk, so it's probably not that popular and I wouldn't like seeing Traefik bloated with too many service discovery backends.

Perhaps it could be written as an adapter like this:

```
Traefik-Consul backend -> tyk-consul-bridge -> Tyk
```

I.e. just configure Traefik to use Consul as backend with address of tyk-consul-bridge, which is a (at point of writing: fictional) program that reads config off of Tyk and serves it over [Consul-compatible API](https://www.consul.io/docs/agent/http/catalog.html#catalog_services).

**Comment by sheerun** [comment]
The point is to run just Traefik, but allow for service discovery through HTTP.

I'd be fine if Traefik implemented HTTP Backend so that it's non-blocking and fetches periodically in background.

**Comment by joonas-fi** [comment]
I believe by "service discovery through HTTP" you mean "service discovery via Tyk", i.e. what you are asking is "Tyk service discovery backend".

HTTP is just a transport, and in fact the Consul backend also works over HTTP, so you could argue that service discovery through HTTP is already implemented. :)

My suggestion still stands, that as Tyk is far less known than Consul etc., so I'd think it'd be easier to write this `tyk-consul-bridge`, which could additionally tap Tyk into other Consul-supported projects like Prometheus and Traefik as well. Kill two birds with one stone, so to speak. :)

**Comment by sheerun** [comment]
> I believe by "service discovery through HTTP" you mean "service discovery via Tyk", i.e. what you are asking is "Tyk service discovery backend".

No, I don't mean to use Tyk through traefik. I just want Traefik to discover services through HTTP.

I just have a Tyk as an example of another proxy that has this feature.

**Comment by joonas-fi** [comment]
Oh all right, my bad!

So what you are asking is a **generic service discovery over HTTP** by allowing to configure an URL to poll and its response format (presumably encoded as JSON) from which to discover the backend services. The configuration would be:

- JSON path from where to find frontend name
- JSON path from where to find backend IP
- JSON path from where to find backend port
- etc etc.
