### ISSUE TITLE
Rancher Provider Improvements

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik#1125]
This issue will be used to keep track of the needed changes, mentioned in #1120 

- [X] Improve Docs
- [X] Reformat Imports 
- [X] Make use of Rancher Service Accounts

**Comment by kelchm** [comment]
@SantoDE, thanks for your work with creating the Rancher provider for traefik.

I've had a look over your contributions in #1120 and #1173 but did not see an obvious way to avoid potential collisions since stacks are not being split out as a subdomain. Traditionally I've structured my domains as the dns providers in Rancher do by default (IE: `<Service Name>.<Stack Name>.<Environment Domain>.<...>`).  Looking forward to your thoughts on the subject. There certainly are some advantages to using a single depth subdomain (using wildcard SSLs and A records).

**Comment by SantoDE** [comment]
Hey @kelchm , 

I can easilly add that :) I guess it makes sense. If you don't want to use that, you could still overwrite the frontend Rule and add what ever domain you want.

**Comment by nuclon** [comment]
There are few more things I would like to add

- Do not ignore stacks/services which are not in "healthy" state (stack and services can go to "unhealthy" or "initializing" state when one of containers is unhealthy even if all other containers are running well. For example - during stack upgrading)
- Make polling interval configurable. Ideally - use websocket event listener for update LB as soon as possible.

I can spend some time and do PRs for Rancher provider.

**Comment by kelchm** [comment]
@nuclon If I can be of assistance with any improvements to the Rancher provider please just let me know. I've not worked with Go before, but I'm highly motivated to get this working a bit more smoothly.

Also, I opened a specific issue related to your first point (#1253) the other day.

**Comment by nuclon** [comment]
@kelchm I've already made my first item locally and it makes things better but still I've got a lot of missed requests. I think that using ws event listener can make rolling upgrades smooth.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
