### ISSUE TITLE
Question on releases

### ISSUE THREAD

**Issue by ralphtheninja** [containous/traefik#1229]
I see `rc` versions coming out and was wondering what the thoughts are on the release schedule. E.g. what determines when the rc versions end in a new "real" release? What speaks against releasing `v1.2.0` today?

**Comment by timoreimann** [comment]
@ralphtheninja thanks for the issue. You raise an important matter.

We (the Traefik maintainers) are currently in the process of deciding on a release cadence. The general idea is to have more predictable cycles so that users have better reliance on when a particular feature will become available.

When to promote a release candidate to a proper release will _somehow_ depend on how stable a candidate is. We'll have to work on defining what "somehow" is; supposedly, metrics like number of open bugs could be an indicator.

We still have to work out a number of details. Let's use this issue to track our progress and call it done once we have a public document available that describes the process.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.
