### ISSUE TITLE
Time.duration config settings not being read in correctly from Traefik.toml

### ISSUE THREAD

**Issue by bparli** [containous/traefik#1342]
### What version of Traefik are you using (`traefik version`)?
Through the latest commit (240b2be)

### What is your environment & configuration (arguments, toml...)?
Go 1.8, logLevel = "DEBUG"

### What did you do?
Tried starting Traefik with ProvidersThrottleDuration set in Traefik.toml.  I tried:

- `ProvidersThrottleDuration = 5`

- `ProvidersThrottleDuration = "5"`

- `ProvidersThrottleDuration = "5s"`

### What did you expect to see?
Traefik starts with the Global configuration indicating ProvidersThrottleDuration is set to 5 seconds.  By default this shows 2 seconds (`"ProvidersThrottleDuration":2000000000`).  I think it should be `"ProvidersThrottleDuration":5000000000`

### What did you see instead?
- The first setting sets it to 5 ns (`"ProvidersThrottleDuration":5`)

- The second setting is actually in the file as an example.  But both the second and third fail with: `Error reading TOML config file /Users/bparli/go/src/github.com/containous/traefik/traefik.toml : toml: cannot load TOML value of type string into a Go integer`

**Comment by timoreimann** [comment]
Coincidentally, I ran into the problem with deserializing `time.Duration` values just today while working on PR 1338.

@emilevauge pointed me at the [README file of the toml parser library we use](https://github.com/BurntSushi/toml/blob/d94612f9fc140360834f9742158c70b5c5b5535b/README.md#using-the-encodingtextunmarshaler-interface) which explains that a custom type satisfying `encoding.TextUnmarshaler` is needed. We probably want to integrate this into staert/flaeg so that we can share a single implementation across many configuration parameters.

I'll work on this as it's blocking my PR.

**Comment by timoreimann** [comment]
NB: This does not seem to affect the CLI parameter equivalents, presumably because they are handled by pflag which comes with a different `time.Duration` parser.

**Comment by timoreimann** [comment]
Relevant PRs have been submitted and are ready for review.

@bparli feel free to take a look too if you like. :-)

**Comment by bparli** [comment]
Thats good stuff @timoreimann.  Thanks for working on it
