### ISSUE TITLE
Traefik serves not healthy tasks in Marathon

### ISSUE THREAD

**Issue by tdna** [containous/traefik#1430]
### What version of Traefik are you using (`traefik version`)?
Traefik: 1.2.2
Marathon: 1.4.2

### What is your environment & configuration (arguments, toml...)?
Provider: marathon

traefik.toml
```
[web]
address = ":8080"
[marathon]
endpoint = "http://marathon.mesos:8080"
marathonLBCompatibility = true
watch = true
domain = "traefik"
filename = "$MESOS_SANDBOX/marathon.tmpl"
```

marathon.tmpl
```
{{$apps := .Applications}}
[backends]{{range .Tasks}}
    [backends."backend{{getBackend . $apps}}".servers."server-{{.ID | replace "." "-"}}"]
    url = "{{getProtocol . $apps}}://{{.Host}}:{{getPort . $apps}}"
    weight = {{getWeight . $apps}}
{{end}}

{{range .Applications}}
{{ if hasMaxConnLabels . }}
      [backends."backend{{getFrontendBackend . }}".maxconn]
        amount = {{getMaxConnAmount . }}
        extractorfunc = "{{getMaxConnExtractorFunc . }}"
{{end}}
{{ if hasLoadBalancerLabels . }}
      [backends."backend{{getFrontendBackend . }}".loadbalancer]
        method = "{{getLoadBalancerMethod . }}"
        sticky = {{getSticky .}}
{{end}}
{{ if hasCircuitBreakerLabels . }}
      [backends."backend{{getFrontendBackend . }}".circuitbreaker]
        expression = "{{getCircuitBreakerExpression . }}"
{{end}}
{{end}}

[frontends]{{range .Applications}}
  [frontends."frontend{{.ID | replace "/" "-"}}-1"]
  backend = "backend{{getFrontendBackend .}}"
  passHostHeader = {{getPassHostHeader .}}
  priority = {{getPriority .}}
  entryPoints = [{{range getEntryPoints .}}
    "{{.}}",
  {{end}}]
    [frontends."frontend{{.ID | replace "/" "-"}}-1".routes."route-host{{.ID | replace "/" "-"}}-1"]
    rule = "{{getFrontendRule .}}"
  [frontends."frontend{{.ID | replace "/" "-"}}-2"]
  backend = "backend{{getFrontendBackend .}}"
  priority = {{getPriority .}}
  entryPoints = [{{range getEntryPoints .}}
    "{{.}}",
  {{end}}]
    [frontends."frontend{{.ID | replace "/" "-"}}-2".routes."route-host{{.ID | replace "/" "-"}}-2"]
    rule = "PathPrefixStrip:/route{{.ID | replace "/" "-"}}"
{{end}}
```

### What did you do?
Updated marathon from 1.4.1 to 1.4.2 (I suspect there are some differences).
Restarted (or submit) an app in marathon.

### What did you expect to see?
Task shouldn't be served in traefik until it gets healthy in marathon.

### What did you see instead?
When a task changes to running state (but it's not healthy yet) traefik starts serving it.

**Comment by timoreimann** [comment]
The current behavior is a bit unfortunate but intentional: Marathon does not persist health checks and thus loses all information during a master re-election. If healthiness was required for an application to become eligible for routing in Traefik, the conclusion would be that all applications would suddenly become unavailable during times where a new master election is in progress. This is a deal breaker for anyone operating a Marathon cluster of decent size.

A current workaround is to enable retries and rely on already healthy apps to receive traffic. The ideal long-term solution is to add support for readiness checks, which can guarantee friction-free rolling upgrades.

Please feel free to chime in on #1185 where the problem has been described in detail and alternatives are considered. I'll be closing this issue in favor of the already existing one. Thanks.

**Comment by tdna** [comment]
Thank you for your reply. Now I can see what the problem is.
Then I don't understand that if the retry number is the number of servers in backend by default how I get a lot of bad gateway error.
For example if I have 4 servers in backend (3 healthy and 1 not healthy) my every 3rd or 4th request gives a bad gateway error.

**Comment by timoreimann** [comment]
@tdna IIRC, the retry value includes the initial request. Did you take that into account? That is, does incrementing the value by one make a difference?

**Comment by tdna** [comment]
Ok but there should remain other 2 retries. Anyway I'll try to increase this parameter.

**Comment by timoreimann** [comment]
Hmm, if you already have plenty of retries, then it should work. I thought you were possibly on the edge.

This at least used to work fine before. Maybe it's a regression.
