### ISSUE TITLE
Does traefik support with etcd version 3 as the backend?

### ISSUE THREAD

**Issue by shenshouer** [containous/traefik#1476]
Does traefik support with etcd version 3 as the backend, if support and How to do?

**Comment by brianredbeard** [comment]
It doesn't at the moment (2017-04-22) because the package used to abstract key value stores ([`libkv`](https://github.com/docker/libkv)) has seemingly been  abandoned.  Folks involved with traffic are working on trying to get all of this fixed up though [1](https://github.com/docker/libkv/issues/103).

That being said, etcd3 does provide a 2.x compatibility API so you can still use the updated 3.x binaries with it.

**Comment by timoreimann** [comment]
@vdemeester any update on the libkv maintenance front?

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
