### ISSUE TITLE
Question on Retry Middleware implementation

### ISSUE THREAD

**Issue by bparli** [containous/traefik#1506]
A general question on your retry middleware, specifically the http statuses that trigger a [retry](https://github.com/containous/traefik/blob/master/middlewares/retry.go#L60).  Is there a reason you only retry on 502 and 504?  I guess you're limiting it to network related errors, but would there be any concerns with including 500 and 503 as well?

**Comment by timoreimann** [comment]
hey @bparli,

please have a look at #1104. The concern towards extending retries to other error codes is that servers returning such codes may have already altered state, and retrying may lead to an undesirable follow-up state.

The currently used codes (502 and 504 as you mentioned) are already troublesome, which is why we plan to change the default to a more sane behavior (retry on refused connections and connection setup errors only and directly, ignoring any response codes) similar to Nginx and HAProxy. It wasn't clear whether users would be interested in having customizable codes to retry on -- if you do, please don't hesitate to chime in on the other issue and let us know!

Does that (and #1104) answer your question?

**Comment by bparli** [comment]
Thanks for the quick response @timoreimann, not sure how I missed that ticket.  That definitely makes sense, I hadn't considered the POST possibility.

**Comment by gopi-ar** [comment]
@timoreimann apologies for opening a closed issue but there are valid use-cases where a proxy layer should handle retries from 5xx errors. For an API service, for e.g., which relies on GET requests that don't alter any server data, a retry by traefik would reduce the need to write such code in application level.

Envoy Proxy has a good document about this: https://www.envoyproxy.io/learn/automatic-retries

**Comment by timoreimann** [comment]
@gopi-ar I agree there are most likely valid use cases. However, this issue was mostly about having a good and safe default which to me still is to restrict retries to network errors. Retry logic building on top of that and leveraging upper layer protocol information (such as HTTP response codes) should only apply for applications that are known to behave accordingly.

Feel free to file a new feature request to discuss your use case.
