### ISSUE TITLE
Kubernetes Ingress Filtering

### ISSUE THREAD

**Issue by dtomcej** [containous/traefik#1728]
Kubernetes ingresses can be submitted by non-administrators to kubernetes clusters. Unfortunately kubernetes does not do any filtering on these objects, and it is possible for someone to submit an ingress that can overwrite other user's ingreses.

I propose that we create some filtering rules so that administrators can filter out ingresses that are submitted that can be damaging.

For example, a user submitting an ingress with a `Path:/` can hijack all traffic on the ingress controller.

I propose both a blacklist and whitelist for Rule types, and Matcher combinations. I propose that if an ingress object is filtered out, a warning be logged, with the details of the ingress, and what blacklist rule it broke to get filtered.

**Comment by djsly** [comment]
Hi @dtomcej , do you think it would be beneficial to have an issue created on the k8s side to allow having the ingress creation to fail if traefik returns the warning ?

**Comment by timoreimann** [comment]
FWIW, we implemented something similar at my work place (outside of Traefik though). If you want to avoid conflicts for sure, you need to rule out that a given path is the prefix of any other path. Otherwise, you open up for the possibility of user A submitting a path prefix `/foo` that serves a resource `/foo/bar`, and a different user B submitting the path `/foo/bar`. IIRC, Traefik prioritizes according to longest path matching, so user B's path would always dominate. (Internally, we call this "URL shadowing").
So if we want to implement filtering, I think we should allow to be this strict.

**Comment by timoreimann** [comment]
Ideally, we can build this feature in a way that it applies for other providers too, such as Marathon.

**Comment by djsly** [comment]
@timoreimann mind sharing how you implemented something similar ? I'm interested to see while we wait for the official support if I could also put something in place. Thanks!

**Comment by timoreimann** [comment]
@djsly the essence of it is really simple: we just iterate over each pair of paths A, B and check if A is a prefix of B (or vice versa). Once we have found at least one case of URL shadowing, we report an error and reject the user request.

**Comment by dtomcej** [comment]
With the implementation of RBAC, Administrators can restrict access to ingresses to specific namespaces. This allows admins to restrict who can submit to what ingress controller, preventing overwrite.

I will close this issue.
