### ISSUE TITLE
Enable Source-Whitelisting per service

### ISSUE THREAD

**Issue by BirgerK** [containous/traefik#1910]
### Do you want to request a *feature* or report a *bug*?

FEATURE

### What did you do?

I already opened a question on [SO](https://stackoverflow.com/questions/45301684/how-to-use-whitelisting-per-container) but there's no answer. Maybe it's not even implemented:
I'm trying to restrict access to dedicated containers on dedicated client IPs.

For this I add a label to my docker-container:
```
labels:
   - "traefik.enable": "true",
   - "traefik.frontend.whitelistSourceRange": "192.168.1.0/24"
```

### What did you expect to see?

Only clients with IP `192.168.1.0/24` can browse to the container. All other client IPs receive a 404.
Every other service is not restricted by this option.

### What did you see instead?

The docker container is reachable from the WWW like every other service.

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.3.4
Codename:     raclette
Go version:   go1.8.3
Built:        2017-07-27_03:52:53PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Running docker-image `traefik:latest`. Running with arguments:
```
"Cmd": [
                "--web",
                "--docker",
                "--docker.watch",
                "--docker.exposedbydefault=false",
                "--acme",
                "--acme.storage=/etc/traefik/acme/acme.json",
                "--acme.email=webmaster@example.com",
                "--acme.domains=example.com,example2.com",
                "--acme.entryPoint=https",
                "--acme.onDemand=true",
                "--acme.OnHostRule=true",
                "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https",
                "--entryPoints=Name:https Address::443 TLS",
                "--defaultEntryPoints=http,https",
                "--traefikLogsFile=/var/log/traefik/traefik.log",
                "--accessLogsFile=/var/log/traefik/access.log",
                "--logLevel=DEBUG"
            ],
```

**Comment by choco1992** [comment]
Hello @BirgerK ,

I had a same problem.
I am not expert in traefik, but if i could help why not. I think the problem is your traefik's version.
I saw you are using version v1.3.4, but  since version v1.4.0-rc1 commited 16 days ago, they added whitelist configuration option (https://github.com/containous/traefik/releases/tag/v1.4.0-rc1).
I update my traefik and it is working.
Could you  update your traefik and try again ?

Regards.

**Comment by ldez** [comment]
please update to https://github.com/containous/traefik/releases/tag/v1.4.0-rc2

**Comment by OverlyExcessive** [comment]
I have a similar issue but basically the reverse problem, we have whitelisted our IP address, but it's returning `403 FORBIDDEN` for us. I suspect it might be because we have an external load balancer infront of traefik, but that load balancer is setting the `X-Forwarded-For` header and when I look through the access logs I can see that the correct remote IP is being printed.

**Comment by joe-bowman** [comment]
@OverlyExcessive - there is already a PR open for this functionality: https://github.com/containous/traefik/pull/1915
