### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by Arsur** [containous/traefik#1922]
**Feature**  

I think the Documentation is bad. Maybe its good if you know what you are doing or you are have experience in web dev , but i guess most people dont have that background.

So my suggestion is to totaly rework the documentation. The get started should just have the information how get every need volume in place (with needed permissions) and the container running and maybe the standart container should have some kind of demo mode where it just creates a sample .toml which makes the UI accessible. (maybe have to enter somewhere their one domain name and define the volumes)  

Than there should be an real documentation itself and not some totaly overloaded examplefiles. Just a place where i can look up every label, grouped by labels. Some larger explanations to every label if needed.

I think the examples should be also reworked. Maybe a hole set of files for every bigger usecase stored in another git folder and than maybe filled with dummy data.
That all presented in better step by step guides (aiming at a more flat learning curve)
I only use dockercompose files. I dont know how other people use docker but i would suggest to hold every example as docker compose. 

I know there are alot of things that i mentioned partly existing, but somehow i found it realy realy hard to get trough the stuff in the way its is at the moment... (I have studied computer science and iam working for an IT company and i still needed so much time and debugging until it worked. Using it with Docker Swarm + 3 Container/microservices + traefik + https is kind of a basic setup ;)...)

Please let me know if iam the only stupid one or if there are more people struggling with this.

**Comment by klud1** [comment]
It all seems you're not alone, tbh i was (100%) not sure where to start...now i'm kinda 80% not sure.

**Comment by ldez** [comment]
We know the problem, we have already thinking about that, it's in our plan.

**Comment by dtomcej** [comment]
Hello @Arsur,

Welcome to the Traefik! As you might not be aware, the Traefik community is largely made up of volunteers, who contribute when they can.

Instead of just complaining about how you had to do some reading and testing, why don't you create a PR with some updates? That way you can contribute to the project instead of just looking whiney.

I would also suggest that if you write a large post complaining, that you use spellcheck, and use proper grammar, as someone who `studied computer science` and `working[sic] for an IT company` should be expected to do.

**Comment by Arsur** [comment]
Hi and thanks for your warm welcome @dtomcej so i guess you are the hater here. Nice that those guys are in every community. Btw iam glad to hear that your mother tongue is english. I would love to speak german with you if you just could. Sorry for the bad spelling but i just wrote this down quickly.
Back to topic.
I know that a git project is community driven, but first of all there are always some maintainers and some users. As developer you get traefik working but you sometimes dont see that others have problems with it and i wasnt sure if iam the only one.

Iam just a user this time and i have my own projects to manage (not on github *avoiding upcoming complains*)

**Comment by mvdstam** [comment]
@Arsur @dtomcej @ldez I've written a Wiki page regarding a use case I've come across (and used myself!). Please feel free to check it out [here](https://github.com/containous/traefik/wiki/Getting-started-with-Docker-&-Let's-Encrypt). 😄

**Comment by ldez** [comment]
@mvdstam great job! Could create a PR instead?

**Comment by emilevauge** [comment]
@Arsur, although we are totally opened to proposals and discussions, I doubt that beginning an issue with "I think the Documentation is bad" will be well perceived in any open source project... Or saying "Than there should be an real documentation itself and not some totaly overloaded examplefiles" cannot be considered as objective...
Your last sentence "Iam just a user this time and i have my own projects to manage" reveals that you ignore the main philosophy of open source: "contribute instead of complaining".
Finally "i guess you are the hater here" shows that you clearly lack of respect to the maintainer team.

Keep cool, learn, and everything will be ok.

**Comment by emilevauge** [comment]
The documentation has been seriously revamped since this issue, and I think we can now close this one.
