### ISSUE TITLE
Redirect based on header value

### ISSUE THREAD

**Issue by dedalusj** [containous/traefik#1924]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

We have Traefik running behind an AWS load balancer. The AWS load balancer is handling the SSL termination and is forwarding traffic to Traefik using the HTTP protocol.

### What did you expect to see?

We would like to be able to issue redirects to HTTPS for requests to the AWS load balancer made using the HTTP protocol. This can be done by inspecting the content of the `X-Forwarded-Proto` header.

### What did you see instead?

Currently Traefik supports two kinds of redirection:

- Blindly redirect HTTP requests to HTTPS. Not suitable since Traefik itself is not handling the SSL termination.
- Redirection with URL rewrite using a regex. Not suitable because not all requests need to be redirect but only the ones with a particular value of the `X-Forwarded-Proto` header.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
v1.3.5
```

**Comment by agabert** [comment]
Please start supporting ingress.kubernetes.io/ssl-redirect as an annotation in traefik.

**Comment by brunzefb** [comment]
I have the same issue -- is this being worked on?

**Comment by brunzefb** [comment]
OK, but will that solve the problem with AWS?  SSL is terminated at the load balancer, and then the traffic is forwarded on port 80 to the traefik container.  The load balancer sets X-Forwarded-Proto to https in that case.  If traffic hits the load balancer coming in on port 80, the load balancer forwards to port 80 and sets X-Forwarded-Proto to http.  Only in that case should traefik send a 301 redirecting to the same address, but with https.

**Comment by lawliet89** [comment]
Traefik 1.6 (now in RC) now supports this. I am using the Consul Catalog backend, and I have added these tags to my services and they work:

```
          "traefik.enable=true",
          "traefik.frontend.rule=Host:example.com",
          "traefik.frontend.entryPoints=http,https",
          "traefik.frontend.headers.SSLRedirect=true",
          "traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https",
          "traefik.frontend.headers.STSSeconds=315360000",
          "traefik.frontend.headers.frameDeny=false"
```

**Comment by mmatur** [comment]
Hi @dedalusj, 

Thanks for your interest in Træfik.

I will close this issue because I think that this feature has been done in version 1.6

Handle by one of PRs listed in #2785

Feel free to reopen it if necessary or to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by npockrus-bnet** [comment]
@mmatur 

Hello, How should I correct this issue in version 1.6? 

I upgraded to version 1.6 and the issue remains. Traefik receives on port 80 yet forwards X-Forwarded-Proto: https and X-Forwarded-Port: 443 which is causing my backend application to error with Unknown SSL protocol.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Træfik, but this issue is now closed :lock:

You can join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

If needed, you can also open a new issue (and follow the [bug](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/bugs.md) or [feature](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/features.md) templates).
