### ISSUE TITLE
Add Service Fabric provider

### ISSUE THREAD

**Issue by jjcollinge** [containous/traefik#2090]
### Do you want to request a feature or report a bug?
Feature

### Problem
[Service Fabric](https://azure.microsoft.com/en-gb/services/service-fabric/) is an orchestration platform built by Microsoft.
The platform currently has very limited routing capabilities without using other 1st party Microsoft cloud services (API Management). By integrating Traefik into Service Fabric we can support much more advanced routing scenarios and it opens up the platform to non .NET software.

Myself and @lawrencegripper have already forked traefik and added a Service Fabric provider. We also have customers who can make use of this and so we thought it might be useful to merge back into the master trunk for others to use. We would also be happy to support future fixes.

### Ask
Before we submit a PR, we wanted to open a discussion to see whether this is something you would consider merging and if you have any reservations or issues.

**Comment by emilevauge** [comment]
Hi @jjcollinge & @lawrencegripper,
Awesome news :heart_eyes: !
We are in the process of adding a plugin mechanism to Traefik, and I think this provider may be a great fit. But we still don't have any ETA on this (golang plugins are not straightforward). In the meantime, we propose you to make a pull request on traefik in order to make a code review by maintainers /cc @containous/traefik. And you are welcome to join us on our [Slack #dev channel](https://traefik.herokuapp.com/) :smile:

**Comment by ldez** [comment]
Closed by #2117
