### ISSUE TITLE
h2c (HTTP/2 without TLS) backend support 

### ISSUE THREAD

**Issue by blop** [containous/traefik#2139]
Would be nice to add support for HTTP/2 backend without TLS, reducing overhead and avoiding the use of selfsigned certificate and backend configuration.

We just need a way to indicate to Traefik that the backend should be contacted using HTTP2 directly (could be a h2c:// scheme in the url maybe?)

Maybe related to https://github.com/golang/go/issues/14141

**Comment by sagikazarmark** [comment]
To be honest I'm confused as hell because of comments like this: https://github.com/containous/traefik/issues/790#issuecomment-257607671

As far as I know, TLS is *not* required for HTTP2, still everywhere I look (even the [documentation](https://docs.traefik.io/user-guide/grpc/)) says it requires HTTPS.

I don't know if there is a blackhole in my mind and completely miss something or as the title says HTTP2 is (intentionally) only supported with TLS in Traefik.

Either way, it would be nice to support HTTP2 without TLS.

**Comment by timoreimann** [comment]
@sagikazarmark you [seem to be correct](https://http2.github.io/faq/). I also remembered this differently, but maybe that was before the final version or the standard was ratified.

FWIW, the linked FAQ states that of the major browsers support unencrypted traffic right now. That doesn't apply to web services, of course.

**Comment by jbpin** [comment]
Hi,
Maybe it's not the right place for this and so doing feel free to indicate me a better place to post this question. 
I have grpc services in container running on docker. I try to do TLS Termination. In this case, Traefik handle http/2 secure communication and internally, request to my gRpc service in the container is insecure. 
```
client with credential SSL -> Traefik -> server with insecure
```
Unfortunately, Traefik try to talk with my server using http/1 and not http/2. 
```
level=warning msg="Error forwarding to http://172.18.0.9:10000, err: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00""
```
Do you know if there is a way to use TLS Termination on Traefik using http/2 ? 
Thanks

**Comment by emilevauge** [comment]
Maybe @juliens can help on this?

**Comment by lachnerd** [comment]
Any Updates on this ?

**Comment by jbpin** [comment]
Not on my side... I don't know why Traefik is translating my request from http/2 to http/1.

**Comment by liukgg** [comment]
Any Updates on this? I think it may be  not necessary to use https when one service communicates to another service by gRPC in the same k8s cluster . Using https in this situation may

**Comment by sbhenderson** [comment]
For those using h2c and gRPC, I found nginx to be capable of gRPC passthrough with proper handling of the HTTP/2 authority header.

I am hoping that Traefik implements h2c handling as it otherwise looks very appealing.

**Comment by gdheller42** [comment]
all my docker swarm services use grpc unencrypted to communicate between then locally. Want to use Traefik since it integrates so well with swarm. Switching to https or TLS is not going to happen though. I will have to continue to use nginx with grpc for now even though it is not able to reresolve the service names if I restart a service.  
Also hoping that Traefik implements http2 without https as grpc does...

**Comment by sagikazarmark** [comment]
Nice 🎉

**Comment by k8s101101** [comment]
I am running kubernetes cluster with Traefic 2.0 ( alpha8) build. With the below ingress configuration, traefik is receiving HTTP2 request and sending HTTP1.2 request to backend.  With the same ingress configuration, http2 request load balanced to the backend correctly. 

Are there any configuration changes that need to be added to Traefik 2.0 to support h2c ?

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: svc1ingress
  namespace : svc1
  annotations:
    kubernetes.io/ingress.class: **traefik**
    **ingress.kubernetes.io/protocol: h2c**
spec:
  rules:
    - host: svc1.k8spoc
      http:
         paths:
           - backend:
               serviceName: svc1
               servicePort: 8080
             path: /userinfo
