### ISSUE TITLE
Manage deprecation

### ISSUE THREAD

**Issue by ldez** [containous/traefik#2212]
### Do you want to request a *feature* or report a *bug*?

proposal

### What did you do?

Deprecated in the future:

- [x] `EntryPoint.Compress`: will become a struct
- [x] `ACME.OnDemand`: will be removed, use `OnHostRule` instead
- [x] By default, don't trust given `X-Forwarded-For`, unless in a whitelist
- [x] `0` server weight disables it (see https://github.com/containous/traefik/pull/1780#issuecomment-335317020)
- [x] Etcd API V2 : `etcd.useAPIV3` will be removed and Etcd v3 become the default.
- [x] suppress old basic auth, move `HeaderField` into basic/Digest auth.
- [x] don't allow dot in the segment name (label)
- [x] drop redundant log fields (ex: `OriginStatusLine` which is just a representation of `OriginContentSize`, `OriginDuration`, and `OriginStatus`)
- [x] remove `passHostHeader` in with KV  (use lower-case key instead)
- [x] replace `http` and `https` as entry point name by `web` and `websecure`

**Comment by dottgonzo** [comment]
why ondemand will be deprecated? is useful for multiple traefik instances, where only the route on try to renew it's certificate, instead of every traefik instances.

**Comment by nmengin** [comment]
Hello @dottgonzo.

> is useful for multiple traefik instances

I guess you want using multiple instances of Træfik in a cluster?
If you want it, the configuration is different.

indeed, you have to use a KV store which will save and share your configuration and your ACME certificates as desbribed in the [documentation](http://v1-5.archive.docs.traefik.io/user-guide/kv-config/#store-configuration-in-key-value-store) and this [user guide](http://v1-5.archive.docs.traefik.io/user-guide/cluster-docker-consul/).

Thanks to this cluster configuration, only the leader instance will create and renew the certificates. The option `onDemand` is not required in this use case.  

WDYT?

**Comment by emilevauge** [comment]
@dottgonzo `ACME.OnDemand` has nothing to do with your cluster issue. I suggest we move the swarm mode + Consul + Traefik discussion from this Github issue to the #support channel on Slack. Thanks :)

**Comment by nmengin** [comment]
The `acme.onDemand` option is deprecated and has to be deleted in the future because of all the problems it can induce.
When ACME has been introduced in Træfik, this option was created to allow users to create easily all their ACME certificates **once** before restarting Træfik without this option.

Indeed, keeping the `onDemand` option has many disadvantages :

* **Slow when requesting a hostname certificate for the first time** : The ACME challenge and the certificate generation are executed on the first request. These operations take time and can lead to **DoS attacks**.
* **Slow requests** : An ACME challenge will be done for all the (sub)domains detected in **all** the requests, even if they do not exist or they are not reachable by the Let's Encrypt server. In this particular use case, every requests will be slow.
* **Rate limiting** : An ACME challenge will be done for all the (sub)domains detected in requests, even if they do not exist or they are not reachable by the Let's Encrypt server. This can lead to exceed the Let's Encrypt [rate limits](https://letsencrypt.org/docs/rate-limits/), and thus prevent from renewing or creating any certificates.

We introduced the `acme.onHostRule` option to replace `acme.onDemand`. Using this, we don't have to wait for the first request to get the certificate as it is created as soon as the backend is deployed. Thus, there is no impact on the reverse proxy performances.

If you are using Træfik in a particular context which does not seem to be compatible with the `onHostRule` option, please give more details on your use case in a comment below.
We will see if it is possible to address your use case and how we can do it.

Thanks in advance.

**Comment by dottgonzo** [comment]
Thanks for your explaination, i understand this limits and months later, when i start to try traefik i've switched from ondemand to onhost rule, due to some issues related to such you just write.

it's hard to explain my use case, it involve the problem of keep separate live streaming connectivity os some containers to the swarm, from theirself and from other kind of request to other containers, so they must access from diferent and precise ip to the swarm (i can't delegate some kind of load balancer or risk that streaming connectivity of an istance full other nodes or block other kind of services), so every traefik/proxy must live separate from others, on the same swarm. I'm looking for a solution to be able to obtain/renew the acme certificates only from the instance effectively reached from that domain. The only one solution seems to be using constraints and associate them manually

**Comment by fkrauthan** [comment]
I actual have a use-case for the on demand rule. We are planning to provision custom sandbox access to our customers. For that we do not know the actual domain at the beginning. With the `onDemand` flag we just need to point the new DNS record to our sandbox environment and it will generate the correct certificate for us. Or what would be the suggested alternative?

**Comment by fkrauthan** [comment]
I think an easy "workaround" for an DoS attack prevention would be calling a external true that returns with status code 0 if the domain is allowed to be issued a certificate and anything else if it is not. That way I can write a simple tool that either queries my database or calls an API server to validate the host file but keeps the flexibility of onDemand certificate generation.

**Comment by dhrp** [comment]
my (our) 2ct as well, regarding OnDemand certificates.

We have a use-case where we allow our customers deploy our software in their own cloud environment through the AWS marketplace. We ask the user to point a domain of their own to our software and have a TLS certificate generated for that address on first request. 

Regarding DDOS attacks (and friends) we may implement a restart with that option OFF after the first certificate was generated. 

Also; (outside the scope of the use-case above).. Not all use-cases of TLS are business critical, and the ease of use of this option can be super helpful. -> So please document the risk, but don't remove the option.

**Comment by fkrauthan** [comment]
Are there any news in regards of supporting OnDemand with optional verification step (e.g. program execution that returns if that domain should be allowed)?

**Comment by mrmachine** [comment]
How does `onHostRule` work with `HostRegexp` rules?

**Comment by kajmagnus** [comment]
Look here how *lua-resty-auto-ssl* lets one specify a callback function for determining if a domain is alowed or not: 
 https://github.com/GUI/lua-resty-auto-ssl#allow_domain  

like you suggested @fkrauthan.

So seems that's a works-fine approach then, I'm thinking.

**Comment by ldez** [comment]
as v2 is now available since 2019-09-16, we will close this issue.
