### ISSUE TITLE
Add restriction level on TLS Mutual Authentication.

### ISSUE THREAD

**Issue by nmengin** [containous/traefik#2288]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Users who define `ClientCAFiles` in a entrypoint may want to allow connections with both TLS mutual authentications and no TLS  mutual authentications on this entrypoint as described in issue #2286.

However _golang crypto library_ does not allow restricting TLS Mutual Authentication to named certificates/domains/routes.

But it's possible to manage the level of restriction. Indeed, today in Træfik when `ClientCAFiles` are provided, TLSConfig is set with `RequireAndVerifyClientCert` which is the level the most rectictive which can be defined as described [here](https://github.com/golang/go/blob/2da8a16cbcd5fc6fc04e1fd8a157cfa21f6d18bc/src/crypto/tls/common.go#L175).

I propose to add a new field in EntryPoint TLS Configuration which allows users to define the level of restriction they want for the TLS Mutual Authentication (the solution detailed below can defer with the final implementation) : 

**Field name :** `StrictTLSMutualAuth`
**Values :** `true` or `false` (`true` => `RequireAndVerifyClientCert` and false => `VerifyClientCertIfGiven` which is less restricitive and allow checking client CA file if provided without generating error if it's missing)
**Default value :** `true` ( `RequireAndVerifyClientCert`).

@containous/traefik WDYT?

**Comment by jaychris** [comment]
I do think this is a worthwhile change - however, it still doesn't address the mixed mode environment model cleanly.  In my current case, I have one endpoint that _requires_ client auth.  I have half a dozen other SSL endpoints that do not.  This change would technically solve my problem (the "all or nothing" scenario, but might not pass muster in terms of audit because it doesn't enforce the auth on the first endpoint.

What I really want to avoid is having to deploy/manage two entirely separate deployments of Traefik - one to enforce client auth and one for everything else.  That seems kind of messy.  

Another solution I have been trying is to run all of my non-auth SSL endpoints on a different port (8443) - but, so far, all I get are TLS errors like this:

```(35) gnutls_handshake() failed: An unexpected TLS packet was received.```

At any rate, I do appreciate this proposed change and it would still be useful for me, even if it doesn't completely address my current issue.  Thanks!

**Comment by nmengin** [comment]
Thank you @jaychris 

The solution you tried seems good to me, I don't understand the errors you have.
Do not hesitate to cotnact us on slack channels if you need more help.
