### ISSUE TITLE
Traefik Documentation Needs an Update

### ISSUE THREAD

**Issue by c0fe** [containous/traefik#2526]
**Page in Question:**

https://docs.traefik.io/

**Comment in Question:**

> Docker¶

> Using the tiny Docker image:

**Command in Question:**

`docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

I kept missing the part that it needs the bind mount to the volume socket.

**Command Should Be:**

`docker run --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock -d -p 8080:8080 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml traefik`

**Comment by rsoika** [comment]
I also want to point out a documentation issue concerning docker swarm mode.
https://docs.traefik.io/configuration/backends/docker/

I did not understand what is meant in the example with the option: 

` endpoint = "tcp://127.0.0.1:2375"`

And I believe this is wrong or maybe deprecated. With this option I can't start traefik - so I leave it to the default value "unix:///var/run/docker.sock"

In general I have so much problems with configuration of traefik in docker swarm. I posted a question in [stackoverflow](https://stackoverflow.com/questions/47622867/why-does-traefik-not-proxy-new-services-in-a-docker-swarm)
Believe me, I try to install traefik since 4 days and 4 very long nights into my swarm - without any success. I am deeply frustrated. 
Maybe you can take a look at docker-swarm section in the documentation to add some additional information? 
I also wrote a short [tutorial](http://ralph.soika.com/lightweight-docker-swarm-environment/) which is including traefik. But this seems to work only  in docker-machine and not with production VMs. I will investigate further and hopefully I finally find out what I am missing. But if you can help it would be great.

**Comment by mister2d** [comment]
@rsoika 
`endpoint = "tcp://127.0.0.1:2375"`

Appears to be an artifact of someone **_wrongly_** assuming that you've set up the docker daemon socket to be accessible via TCP. The Docker TCP socket is not enabled by default, so this tcp statement shouldn't be there in the first place.

`endpoint = "unix:///var/run/docker.sock"`
Remains valid, especially when one simply bind maps in the docker socket in a run statement or using docker-compose.

**Comment by rsoika** [comment]
yes, this is what I mean. The docker-swarm example at  https://docs.traefik.io/configuration/backends/docker/ should be changed in this way

replace
`endpoint = "tcp://127.0.0.1:2375"`
with 
`endpoint = "unix:///var/run/docker.sock"`

**Comment by mmorejon** [comment]
Hi team,
My environment settings are:
```
os: ubuntu 16.04
docker: 18-01.0-ce
```
Docker daemon has been configured for `unix:///var/run/docker.sock` and `tcp://0.0.0.0:2375`.

My question is: If I use as endpoint `unix:///var/run/docker.sock` or `tcp://0.0.0.0:2375` can I avoid the `volumes` section into `docker-compose.yml` file?
I was expected that yes but Traefik doesn't starts. Any suggestion?

**Comment by dtomcej** [comment]
Hello All.

The new documentation pages have the suggested recommendations applied:

1. Docker socket bind mount applied in the documentation
2. Docker endpoint updated to the unix socket, with a note that tcp endpoints are also accepted

Since all of the suggestions in this issue have been implemented, I will close the ticket.

Thanks!
