### ISSUE TITLE
Kubernetes Docs: extremely poor naming convention

### ISSUE THREAD

**Issue by peterdeme** [containous/traefik#2531]
Hi Guys,

So I'm setting up my playground cluster with Traefik and reading this article: https://docs.traefik.io/user-guide/kubernetes/

I noticed that literally **everything** is called traefik-ingress-controller. Why? Why is an RBAC role is called traefik-ingress-controller instead of traefik-discovery-role or something like that? Service, ingress, deployment, role, role-binding, service account all of them is called that way. My head hurts so much figuring out what is what, I wonder why is it even working. 

The other thing. I'm just starting to get to know Kubernetes but is it a good practice to put everything to **kube-system** namespace as the article suggests to do? For me this namespace sounds kinda like C:\Windows folder - just don't mess with it, let it do its work.

### Do you want to request a feature or report a bug?
Let's say feature.

### What did you do?
Setting up a Kubernetes playground cluster with the guidance of the official docs.

### What am I expecting to see?
Correct, understandable naming convention.

### What I actually see?
Everything is named traefik-ingress-controller which makes hard for people to understand what Kubernetes component does what. Btw, this is how I edited mine to fit my greedy needs: [Git gist](https://gist.github.com/peterdeme/5ffced408be95a50cfb40ac7a8d03bd5) - might be a good place to start. Here "sd" stands for service discovery.
### Traefik version, environment, platform, OS
Doesn't matter.

**Comment by traefiker** [comment]
Every time someone does not respect the issue's template, a little bunny dies.

<details>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)
![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>
<br>

Please edit your issue description to respect the [issue template](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE.md) as much as possible.

**Comment by peterdeme** [comment]
Right, sorry, I updated my comment.

**Comment by timoreimann** [comment]
Every object in Kubernetes consists of a type (or kind) and a name. It is not too uncommon to name all objects related to a particular application equally if there's no need to have more than one object per type. I actually believe this can simplify working with all objects related to Traefik dramatically because your `kubectl` invocations will always follow the same pattern: `kubectl <verb> <type> traefik-ingress-controller`. Personally I'd probably feel bothered very quickly if I had to remember the right type-specific name with each operation.

Regarding the namespace, it depends: some people like to put all "system-critical" applications into the kube-system namespace since it's traditionally been fairly unrestricted. These days, I don't think it's necessary anymore and you can choose any namespace that fits your needs. It's difficult to come up with a one-size-fits-all recommendations, however, because there are a lot of legitimate possibilities to provision Traefik. For instance, you could use one Deployment per namespace (e.g., _development_, _staging_, and _production_) or use a single Deployment  (or Daemonset) for the entire cluster.

What our guide may need is a big fat note stating that it is not meant to be the perfect production-ready setup but rather a working baseline that users can start tweaking and customizing from.

**Comment by peterdeme** [comment]
I see. Looks like Prometheus does the same thing [here](https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml). Wasn't aware of this weird convention. Then I think it can be closed.
