### ISSUE TITLE
Feature Request: multiple acme entry points

### ISSUE THREAD

**Issue by raarts** [containous/traefik#2710]
### Do you want to request a *feature* or report a *bug*?

feature request

### What did you do?

It's currently impossible to share acme certificates between entrypoints.
See: https://stackoverflow.com/questions/47277489/traefik-multiple-https-entry-points-with-acme-letsencrypt-dns

Something similar to this:

    --acme.entryPoints=[https,stream] \
    --acme.entryPoints.https.dnsProvider=digitalocean \
    --acme.entryPoints.stream.dnsProvider=vultr \

**Comment by isrjo** [comment]
+1

**Comment by colinmollenhour** [comment]
+1 Example, I am running both https and etcd in readonly mode on one server on different ports (443 and 2379) but want them both to use Let's Encrypt and actually share the same certificate. Currently it looks like I'd have to run two instanced of Traefik but then unless I use a KV store then I'd have two separate certificate stores.

**Comment by adyromantika** [comment]
👍

**Comment by jnovack** [comment]
"multiple acme entry points", to me, means that I can have multiple values in `acme/entrypoint`.  It does not imply that sites should be able to available on multiple TLS entrypoints.

```
[acme]
entryPoints = "https1,https2"

[acme.httpChallenge]
    entryPoint = "http"
```

Using this configuration, I would expect sites (`Host:xxx.example.org`) to be XOR (exclusive OR, one or the other, not both) on entrypoints.

This means to me:

* `site1.example.org` can be presented on `http` and `https1` entrypoints, and
* `site2.example.org` can be presented on `http` and `https2` entrypoints, and
* `site1.example.org` CANNOT be available on `https2` entrypoint, and
* `site2.example.org` CANNOT be available on `https1` entrypoint.

I would expect to use the same FILE of certificates on both entrypoints, but I would not expect to use a certificate on multiple entrypoints.

This interpretation seems to be different from the feature request as stated, and probably easier.  I believe the original poster is asking for:

* `site1.example.org` can be presented on `http`, `https1`, and `https2` entrypoints, and
* `site2.example.org` can be presented on `http`, `https1`, and `https2` entrypoints

**Should I make a separate Feature Request for my interpretation?**

**Comment by snowzach** [comment]
I opened PR 4345

**Comment by Rush** [comment]
@snowzach I don't think your PR would work for all cases. My use case is:
- One IP is providing one set of services.
- Secondary IP is providing a second set of services.

I want an entry point for each of the IPs to provide ACME with httpChallenge independently.

I believe a real `entryPoints = [ "https-ip1", "https-ip2" ]` would solve the issue.

Note: I am super new to traefik - please correct me if I'm wrong :)

**Comment by ederion** [comment]
So is snowzach's PR getting reviewed and merged anytime soon? I miss this feature as well.

**Comment by snowzach** [comment]
@Rush that's a tricky one. I think you would need even more config that might more easily be solved by just running 2 instances of traefik, one per IP address. The situation you describe would require basically 2 entire sets of acme configuration because the verification and domain information is a single setting I believe. The solution is probably refactoring the entire acme config to sit under an entrypoint vs one global acme config.

**Comment by Rush** [comment]
@snowzach yes, I ended up running 2 instances of traefik for each of the IPs however from a pure architectural point of view de-globalizing acme and making it per-entrypoint  (or even per domain?) would be the most robust/flexible solution.

I wrote a reverse proxy in Node.JS with Acme support in the past (https://github.com/virtkick/http-master#readme) and my solution was to have a per-domain ACME method/account selection.

This way one set of domains could be handled with say, Cloudflare DNS challenge, and another set of domains could be handled with a different account and method ...  who says you should have all of your domains on one DNS provider.

**Comment by eigengrau** [comment]
Chiming in with our use-case: We would like to expose certain services on an entrypoint that is bound to a VPN-only interface/port. However, some of these services mandate TLS (e.g., Docker registry), so our VPN entrypoint still needs to be TLS-enabled. Hence, it would be convenient for us if frontends set-up on the VPN entrypoint would still trigger ACME certificate aquisition on a publically accessible entrypoint. Is this use-case something already covered by the work that went into 2.0?

**Comment by CybotTM** [comment]
Hi,

is this still an issue with 2.0?

**Comment by dduportal** [comment]
Closing as per Traefik v2.0 implements a new system for ACME: https://docs.traefik.io/v2.0/https/acme/

**Comment by jnovack** [comment]
It's not clearly laid out, but the original issue is solved and my original posed question is unknown.

The best clue as to how lies in the [routers#general](https://docs.traefik.io/v2.0/routing/routers/#general) page, with an example provided.

The example suggests you can have the same endpoint on two different routers, since Traefik is doing the SSL termination.  However, this is not explicitly stated.

The example also provides insight to using Mutual TLS (or Client Authentication); since mTLS or ClientCA settings are defined under `options`, you MUST only have one (1) set of options per Hostname.

So while you explicitly can not have `https://snitest.com/user` and `https://snitest.com/admin` with different `ClientCA` options, you may *(it is unclear, but my interpretation)* have `https://admin.snitest.com` and `https://user.snitest.com` with different `ClientCA` options.
