### ISSUE TITLE
ConsulCatalog provider: should not retrieve the node ip but the container ip

### ISSUE THREAD

**Issue by samber** [containous/traefik#275]
Hi guys,

One of the best practice with Docker Swarm is probably to never expose container ports to the host and communicate only through Docker Networks. It allows to: 
- see a container "as a machine", 
- always discuss with the same -internal- port
- be host-agnostic.

FYI, I'm using gliderlabs/Registrator with "-internal" to register services into consul, send the container address in the docker network.
Each of my aws virtual machines can host multiple containers of the same services. Registrator is registrating both:
- the node ip (in /v1/catalog/node/<node>)
- the container ip (in /v1/catalog/service/<service>)

The [consul catalog template](https://github.com/containous/traefik/blob/master/templates/consul_catalog.tmpl) is: 
- Naming the backend according to the node name: conflict when 2 containers of the same service are on the same host.
- Using the node address instead of container address: conflict when 2 containers of the same services are on the same host.

I suggest:
- using Service.ID as backend name (unique in the consul catalog)
- using Service.Address (=container ip) as address, **BUT** if your Traefik instance is not containerized and/or doesn't access to the Docker Network, it makes a **breaking change**.

Shall we follow the best practice or add a new flags to ```traefik.toml``` for backward compatibility ?

**Comment by emilevauge** [comment]
Hi @samber, I also prefer the container ip way, and this is one of the goal of traefik after all ;)
I would go on your suggestion, because I don't really see the point of deploying a traefik instance in a different network. Even if someone is in this case (and I really cannot imagine that ^^), it could be solved using a customized template right ?

**Comment by keis** [comment]
Using Service.Address sounds like the correct thing to do. I think I was just being lazy and used what worked rather than fix so I didn't register services with unroutable addresses in Service.Address.

It's host+port so no conflict even when on the same host but again using ID sounds more correct :+1:

**Comment by samber** [comment]
Done.
FYI, the Service.ID is not unique, then i used service name + service ip + service port

**Comment by emilevauge** [comment]
Closing this one, to be continued here #309
