### ISSUE TITLE
Why does ingress annotations have two equal name? 

### ISSUE THREAD

**Issue by yue9944882** [containous/traefik#2819]
### Do you want to request a *feature* or report a *bug*?
*feature*

### What did you expect to see?

`ingress.kubernetes.io/xxx` and `traefik.ingress.kubernetes.io/xxx`

I think traefik should only support one form of annotations. This can confuse us user a lot, or it can waste our time on finding out if there are differences. Actually I believe they are the same [https://github.com/containous/traefik/blob/c0563f1a395d53edbbf1030b2387435077eeb871/provider/kubernetes/annotations.go#L71](https://github.com/containous/traefik/blob/c0563f1a395d53edbbf1030b2387435077eeb871/provider/kubernetes/annotations.go#L71)

[https://github.com/containous/traefik/blob/master/docs/configuration/backends/kubernetes.md](https://github.com/containous/traefik/blob/master/docs/configuration/backends/kubernetes.md)

Especially in the documentation of kubernetes provider, both forms are mixed together which may  make it even worse.

### What did you see instead?

`ingress.kubernetes.io/xxx` and `traefik.ingress.kubernetes.io/xxx` works equally the same.

**Comment by ldez** [comment]
In v1.5, we have a mix of annotations prefixes: http://docs.traefik.io/configuration/backends/kubernetes/#annotations

From the documentation in **master** and related to the experimental version (future 1.6): 
> traefik.ingress.kubernetes.io/ and ingress.kubernetes.io/ are supported prefixes.

http://docs.traefik.io/master/configuration/backends/kubernetes/

We have made this decision because currently there is no real naming convention for k8s annotations:
- https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md
- https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md
