### ISSUE TITLE
Do not pull the whole state when receiving update on Marathon

### ISSUE THREAD

**Issue by alenkacz** [containous/traefik#2956]
### Do you want to request a *feature* or report a *bug*?

*feature* but also kind of *bug* :)

### What did you do?

On Marathon event https://github.com/containous/traefik/blob/fb4ba7af2b6617ab6ef24bfca12f04deb207edb8/provider/marathon/marathon.go#L131 Traefik is pulling the whole Marathon apps state from the endpoint https://github.com/containous/traefik/blob/fb4ba7af2b6617ab6ef24bfca12f04deb207edb8/provider/marathon/config.go#L89

That's not the most performant way to do that especially since on a bigger clusters pulling all apps means that Marathon have to serialize huge jsons.

Better approach would be to parse the event and update only the app that the event references. With a small guidance I would by happy to do some contribution in that direction.

**Comment by timoreimann** [comment]
@alenkacz thanks for your feature request.

I agree that fetching all applications on each event is wasteful per se. The approach you describe would certainly boost efficiency.

However, there is a downside to the proposed improvement: If an event is lost or cannot be processed for whatever reason, it might be difficult to remedy the situation. Conversely, the existing approach always fixes any inconsistent state on the next successfully processed event. There are ways we could deal with this though, at the price of some extra effort.

If JSON deserialization is truly a performance bottleneck, an easier fix might be to use a faster JSON library (such as json-iter). The stdlib version is known to be sub-optimal in this regard.

Can I ask if you have personally experienced performance issues due to the cost related to fetching all applications in the current implementation? I am fine with considering alternative approaches, but we should first try to collect data demonstrating the need.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
