### ISSUE TITLE
Traefik in docker swarm cluster mode:  Traefik not running on the manager node

### ISSUE THREAD

**Issue by TingShingIp** [containous/traefik#3019]
**CONTEXT**
Our swarm cluster mode setup is 1 drain manager node + 4 active worker node.  Our manager node is drain because we do not want to overload the manager with container which can lead to losing the manager and losing the complete swarm. Because the manager is in drain mode we cannot use Traefik. quote in the documentation:
_"The only requirement for Træfik to work with swarm mode is that it needs to run on a manager node - we are going to use a constraint for that."_ 

**FEATURE**
Would it be possible to run traefik not in the manager mode?

**WORKAROUND**
- Using another type of swarm cluster mode (example: 3 active manager node + 1 active worker node).  The issue our company do not want to change the cluster setup
- Active the manager node (1 active  manager node + 4 active worker node) and adding  constraint in containers that only the traefik container node is allow to run on the manager node.

**Comment by nmengin** [comment]
Hello @TingShingIp .

Many thanks for interest in the project.

Træfik needs to listen to the Docker Swarm API to update its configuration.
Unfortunately, today Docker Swarm does not allow to listen to its API from the worker nodes.

That's why we cannot do this feature.

I close the issue but feel free to join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
