### ISSUE TITLE
Allow configurable response for non-SNI requests

### ISSUE THREAD

**Issue by tomtastic** [containous/traefik#3095]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you do?

Traefik is responding with its certificate 'TRAEFIK DEFAULT CERT' for non-SNI aware clients,
please provide a configurable option per frontend to set a domainname
certificate to return.

eg.
When a non-SNI aware client requests TLS secured traffic from www.domain.name,
consult something like the below imagined option to respond with the certificate for www.domain.name, rather than the 'TRAEFIK DEFAULT CERT' :

`traefik.frontend.xyz.nonSNICertDomain=www.domain.name`

**Comment by lucwillems** [comment]
hi all ,
i also have currently a issues with a customer which uses tools which doesn't seem to support SNI.
There where complaining about bad "TRAEFIK" certificates which was not allowed by there corporate security policy. The fact that we present a self signed certificate is maybe not so good response.

i would like to see that clients which do not support a valid SNI connection, we log a error about this client (ip address) and drop the connection completely. This way we see this kind of connections error quickly en inform our customer that they need to to use more "modern" tooling /libraries .

my point of view is that if you don't support SNI , which is critical to have many site hosted using single ip , you beter upgrade your tooling or just leave and go fishing. SNI is so old (introduced in RFC3546 , in 2003 ) . if the client doesn't support this , he's better of to not go on the internet , because how well will his stack be protected against all issues currently known .

so something like "drop non SNI client " feature would greatly help this.
something simular like apache has (http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslstrictsnivhostcheck)
