### ISSUE TITLE
support ingress.kubernetes.io/add-base-url annotation

### ISSUE THREAD

**Issue by jeroenjacobs1205** [containous/traefik#3125]
### Do you want to request a *feature* or report a *bug*?

Feature 

### What did you do?

Added ingress.kubernetes.io/add-base-url annotation to a kubernetes ingress rule, as documented here:https://docs.giantswarm.io/guides/advanced-ingress-configuration/#rewrite. This is for nginx-based ingress controller

### What did you expect to see?

I was hoping Traefik also supported this annotation, and re-write the base url.

### What did you see instead?

base url was not overwritten. I couldn't find the annation here:https://docs.traefik.io/configuration/backends/kubernetes/

However, I think it would be a nice feature to add.

**Comment by Juliens** [comment]
Thanks for your interest in Træfik!

We think that the process of rewriting the response body in a reverse proxy is too heavy/prone to errors. That's why we don't support the annotation `ingress.kubernetes.io/add-base-url`.

We encourage you to either:
- use host based rules only
- use specific Traefik path rewrite headers in you app (X-Forwarded-Prefix, X-Replaced-Path)
- let your app listen on a specific path
