### ISSUE TITLE
Customize Kubernetes health check of services

### ISSUE THREAD

**Issue by cemo** [containous/traefik#3220]
In my dashboard, I have noticed that I have some 404 requests. I have searched issue tracked and source codes but could not find a solution. Is it possible to configure health check resources of kubernetes? Since some of my services are using different endpoints for health checks, I would like to configure them.

Please provide necessary support for customizing `ingress` resources of kubernetes.

**Comment by timoreimann** [comment]
Traefik implicitly leverages liveliness and readiness probes defined on pods: as soon as the kubelet seems one of them failing, the corresponding endpoints will be removed by the Endpoints controller, which in turn will trigger an update in Traefik to omit the affected backends accordingly.

In a nutshell: just configure the mentioned probes in your pods, deployments, etc. and you should be fine.

**Comment by timoreimann** [comment]
I'm going to close the issue. If you think my response does not address your request, please don't hesitate to comment again so that we can reconsider. Thanks.

**Comment by cemo** [comment]
Thanks @timoreimann I will check in detail and share my insights. Would you share me an easy way to spot those 404 in my `dashboard/health` please? I noticed that there is https://github.com/containous/traefik/pull/2443 but this could not help me a lot. It might be related something else.

**Comment by timoreimann** [comment]
@cemo that PR you're referring to is about Traefik's very own health checks. They are not really needed when using the Kubernetes provider because liveliness and readiness probes are far more powerful and flexible. If you have enabled Traefik health checks for Kubernetes, I suggest to remove them and configure probes instead.

As to why you're seeing 404s: please jump onto our Slack channel or open a Stackoverflow question. It'll be easier to debug your issue on one of those channels. Feel also free to mention/ping me. 

Thanks!
