### ISSUE TITLE
Memory Leak / CPU Exhaustion with trailing dot

### ISSUE THREAD

**Issue by wwaites** [containous/traefik#3269]
### Do you want to request a *feature* or report a *bug*?

Definitely a bug

### What did you do?
I started traefik as described at https://docs.traefik.io/#1-launch-trfik-tell-it-to-listen-to-docker

I then made two slightly different HTTP requests:

```
    curl -H "Host: traefik.traefik" http://192.0.2.1/
    curl -H "Host: traefik.traefik." http://192.0.2.1/
```

### What did you expect to see?

I had hoped to see the admin interface (rather than using port 8080, but that is not the problem)

### What did you see instead?

The first request yielded a 404 response code. The second request caused traefik to consume all available memory and CPU.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
docker image 28da388cd99a (built 37 hours ago)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Default configuration.

**Comment by traefiker** [comment]
Thanks for opening this issue!

We need further information to better understand the problem you're facing :thinking:

Could you please join us on our [Slack workspace](https://traefik.herokuapp.com) and reach out to us on the ([#support channel](https://traefik.slack.com/messages/C0CDT22PJ/))?

We're looking forward to talking to you there!

**Comment by geraldcroes** [comment]
Hi and thank you for your update. 

The problem you face looks like something we are aware of (and able to reproduce) that happens when there is a misconfiguration that leads to a loop. 

For example, when you deploy traefik as a container on your docker cluster, the container (with the provided tutorial yaml file) exposes both the port 80 (that handles the routing) and 8080 (that handles the UI). 
If you tell traefik to listen to docker (through docker.sock), traefik will  detect its own container and will automatically create a route to that container, using port 80 (that handles the routing) as a default, and not 8080 (the dashboard).

The above leads to a situation where you send traffic to traefik, that sends the traffic to traefik, that sends the traffic to traefik, that -- you get the drill -- gets nothing good done.

But to be sure that this is the problem you're facing, we need more details about your set up.

What is the "default" configuration file you're talking about? What is your OS? ... at which step of the linked tutorial are you stuck? Have you made changes to the docker-compose.yml? What are the deployed containers?

To double check, I've checked out 1.6 and did the tutorial you've linked with no problem.

If you have an email, you can create a slack account in a matter of seconds and we'll be able to help you out more efficiently. If not, feel free to keep using this issue.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
