### ISSUE TITLE
[Whitelist] X-Forwarded-For Spoofing Protection

### ISSUE THREAD

**Issue by zebulon99x** [containous/traefik#3646]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Environment: Kubernetes 1.10.4
Traefik Version: 1.6.5

Currently, if the whitelist for an ingress is using X-Forwarded-For headers with a list of IPs then Traefik will allow a request through if any of the IPs in the forwarded list are allowed by the whitelist. This makes spoofing requests very simple for malicious attackers. I'm currently working behind Amazon ALBs and would like the option to only check the most recent X-Forwarded-For host added to the list. The ALB will always add the host of the incoming request to the end of its X-Forwarded-For header.

It also seems likely to me that some people might prefer for the whitelist to require all IPs in the forwarded header to match the whitelist as well in an environment that requires enhanced security.

**Comment by jbdoumenjou** [comment]
Hi @zebulon99x , thank you for your interest in Træfik.
We will improve the X-Forwarded-For behavior and configuration in the next version (#3778) .
For now, you can trust only the requests from your ALB.

**Comment by zebulon99x** [comment]
Excellent, excited for the 1.7.0 release to test this out.

**Comment by geraldcroes** [comment]
If we all agree, I will close the issue.

**Comment by jbdoumenjou** [comment]
Sorry @zebulon99x, I was not clear, it is not fixed in the 1.7 but in the version after (#3778)

**Comment by LordMike** [comment]
I'm encountering odd behaviour where I'm running behind Cloudflare, but without additional configuration, the Cloudflare X-Forwarded-For header is "trusted".. I expected to add `ForwardedHeaders.TrustedIPs:...cloudflare....` to Treafik to trust its headers.

Is that covered by this issue?

For Whoami, I'm seeing my IP (and cloudflares), both on X-Forwarded-For, which I'd only expect if Traefik trusted Cloudflare. Docs say that by default only some private ranges are trusted.

**Comment by LordMike** [comment]
Adding to the above. I have another service running in Docker behind traefik, where I want to use `traefik.frontend.whiteList.sourceRange` to whitelist some ranges of users (our office basically) that can connect to this service. Since the service is behind Cloudflare, it didn't work, as Cloudflare wasn't our office. 

I've been able to make it work by also specifying `traefik.frontend.whiteList.useXForwardedFor` to `true`. But that's where my confusion comes in, because I haven't specified that Cloudflare is an authenticated proxy (previous comment), so traefik shouldn't trust the X-Forwarded-For from Cloudflare.

... is it that `traefik.frontend.whiteList.useXForwardedFor` will trust ALL IPs in the forwarded for, and check if ANY of them match ANY allowed source?.. :|

**Comment by jbdoumenjou** [comment]
As X-Forwarded-For's behavior has been improved in v2, I will close this issue.
