### ISSUE TITLE
Access log records the wrong frontend name

### ISSUE THREAD

**Issue by glennschmidt** [containous/traefik#3663]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Using the consul config provider, create several frontends (with different Host rules) and point them to the same backend.
2. Turn on the `accessLog` feature.
3. Make a HTTP request to one of the frontend domains.

### What did you expect to see?

The log message includes the name of the frontend matching the domain of the HTTP request.

### What did you see instead?

The log message always seems to show the first frontend (alphabetically) from consul.

### Output of `traefik version`: (_What version of Traefik are you using?_)

1.6.4

**Comment by mmatur** [comment]
Hi @glennschmidt,

Thanks for your interest in the project.

After some investigation, I am not able to reproduce your issue.

Could you please provide us your Træfik configuration, your traefik access log , your traefik debug log and  if it is possible a compose file to be able to reproduce your issue.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
