### ISSUE TITLE
ACME Client building on worker instead of master nodes

### ISSUE THREAD

**Issue by alwinmarkcf** [containous/traefik#3762]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I'm not quite sure if this is a bug but it seems weird to me.
From my understanding only the leader should create an LE Account and try to get certs. In fact as I read it, its currently implemented the other way arround:

https://github.com/containous/traefik/blob/v1.7/acme/acme.go#L131
```golang
	listener := func(object cluster.Object) error {
		account := object.(*Account)
		account.Init()
		if !leadership.IsLeader() {
			a.client, err = a.buildACMEClient(account)
			if err != nil {
				log.Errorf("Error building ACME client %+v: %s", object, err.Error())
			}
		}
		return nil
```

but maybe I'm completely wrong.

### What did you expect to see?

Only the leader tries to create ACME account

### What did you see instead?

Every node except the Leader is creation an Account. (At least that's what I believe to see).

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
(paste your output here)
```

**Comment by geraldcroes** [comment]
Hi and thank you for your efforts in tracking down potential problems.

What you missed is that the leader has its own leadershipListener (https://github.com/containous/traefik/blob/v1.7/acme/acme.go#L179) in charge of dealing with certificates (onHost / acme.domains / ...) with its own ACME Client.

The ACME Client that exist in the "non leaders" is to handle the deprecated (but still supported) onDemand option (since we have no guarantee that the leader will be the first to handle the request targeting a new onDemand host).

I will let you confirm that it fixes your concern and close the issue.
