### ISSUE TITLE
Simple block all robots.txt 

### ISSUE THREAD

**Issue by trajano** [containous/traefik#3839]
Instead of creating a separate path map pointing to an nginx server serving a single robots.txt or (that contains

```
User-agent: *
Disallow: /
```
or using https://hub.docker.com/r/wikiwi/robots-disallow/

Can you provide a single command line option that we can enable on our staging environments?

**Comment by kachkaev** [comment]
Adding this feature would open a pandora box IMO. If robots.txt is served directly by traefik, why not favicon, shared error pages and so on? I think it’s better to keep traefik clean instead.

**Comment by trajano** [comment]
I'm not saying to serve a robots.txt file that is from the file system but something that is explicitly hard coded to just disallow robots.

**Comment by kachkaev** [comment]
That will still mean that traefik will be serving some file, which it never does now. This will create an unwanted precedent IMO.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
