### ISSUE TITLE
Add support for DNS alias mode (`--challenge-alias` flag) for Let

### ISSUE THREAD

**Issue by Tuckie** [containous/traefik#3846]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Requesting support for the [DNS Alias Mode](https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode) with acme / Let's Encrypt.

This would allow me to use an ` _acme-challenge` subdomain on a provider that does not have api support.

**Comment by geraldcroes** [comment]
Hi and thank you for your message.

I think that the feature you're looking for already exists. Have you looked into the exec provider with ACME? https://docs.traefik.io/configuration/acme/

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
