### ISSUE TITLE
Support creating service on consul based on frontends

### ISSUE THREAD

**Issue by lfdominguez** [containous/traefik#3922]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I have 2 traefik on 2 differents overlay networks. I want that every frontend registrered on traefik was registred as service on consul, so when i query the consul DNS server can get the traefik address to my frontend services

**Comment by dduportal** [comment]
Hi @lfdominguez , thank for your interest in the project.

This feature is not something which could be done, because how Traefik is working: Consul should be use as a "backend" system, to provide information for Traefik to dynamically configure itself, and not the opposite.

Depending on the kind of backend (you want the services to be declared into Consul) currently used on your Traefik instances, maybe it should be worth it to feed Consul with your backend services instead. If you are using Docker, this could help: https://github.com/gliderlabs/registrator .

**Comment by lfdominguez** [comment]
> Hi @lfdominguez , thank for your interest in the project.
> 
> This feature is not something which could be done, because how Traefik is working: Consul should be use as a "backend" system, to provide information for Traefik to dynamically configure itself, and not the opposite.
> 
> Depending on the kind of backend (you want the services to be declared into Consul) currently used on your Traefik instances, maybe it should be worth it to feed Consul with your backend services instead. If you are using Docker, this could help: https://github.com/gliderlabs/registrator .

I see your point, but when a service is registered into Consul, get the real internal IP that catch traefik, that's ok, but i need that when i query de Consul DNS, the IP returned was the traefik external ip, not service internal ip....
