### ISSUE TITLE
Support --ingress-class option in Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by raravena80** [containous/traefik#3950]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Add a command line for the Kubernetes Ingress Controller to support `--ingress-class`.  The use case here would be multiple ingresses. Currently, the nginx ingress controller supports it.

Some background here: https://stackoverflow.com/questions/52557930/traefik-on-kubernetes-does-not-keep-path-over-redirect

**Comment by nmengin** [comment]
Hello @raravena80 

Many thanks for your interest in the project.

The feature seems to exist in the version 1.7 (#3516).

I close the issue because I guess the question is answered, but feel free to reopenit if necessary or join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
