### ISSUE TITLE
Add Extra Example To https://docs.traefik.io/configuration/entrypoints/

### ISSUE THREAD

**Issue by finguk** [containous/traefik#4019]
Currently there is no documentation for extra bound ports on https://docs.traefik.io/configuration/entrypoints/

Suggest adding in something like:

[entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
[entryPoints.extraporthttps]
  address = ":5555"
    [entryPoints.extraporthttps.tls]
      [[entryPoints.https.tls.certificates]]

Make it clear that entryPoints.XXX can be a pointer and not a service name.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
