### ISSUE TITLE
Question: How to remove backend prefix to docker containers?

### ISSUE THREAD

**Issue by JemiloII** [containous/traefik#4024]
When I create the label:
`traefik.backend: aoh` in my docker-compose file, traefik adds `backend_aoh` instead of `aoh`, how can I remove that? If I manually set the rules in the toml file, I can get the backend to be named `aoh` by using `[backends.aoh]`

**Comment by dduportal** [comment]
Hello @JemiloII , thanks for your interest in the project!

This naming is internal, and depends on dynamic generation from Docker.
You don't need to change this since it is not related to any configuration.

If you have any question, do not hesitate to use the slack channel: https://slack.traefik.io/ .
