### ISSUE TITLE
Kubernetes Ingress not working: abort Handler

### ISSUE THREAD

**Issue by unamuno** [containous/traefik#4030]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I Configured Trafik acording to the kubernetes guid on the doku.

### What did you expect to see?
The Webpage of a simple Nginx Pod for https, http

### What did you see instead?
White page, not loading

In the kubernetes log of the deamon set i found:
`
level=error msg="Recovered from panic in http handler: net/http: abort Handler"`
And
`level=error msg="Undefined entry point(s) 'https' for <DOMAINNAME>"`
Set in  your domain name. 

### Output of `traefik version`: (_What version of Traefik are you using?_)

I used the file:
 https://raw.githubusercontent.com/containous/traefik/master/examples/k8s/traefik-ds.yaml
To deploy Traefik and changed the settings for TLS suport.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

I use the latest Kubernetes Version v1.12.1 on Ubuntu 18.04. LTS

**Comment by dduportal** [comment]
Hell @unamuno , thanks for your interest in the project.

?ould you provide us the following elements?

- The Traefik version used (since it is specified `latest` in the YAML for Daemonset).
  * If it is 1.7.2, could you try with the image `mmatur/traefik:fix-recover-from-panic` and let us know if it is working?
- Could you show us the Ingress Rule you used for the "nginx backend Pod" please? Any other Kubernetes informations using `kubect describe ...` could be helpful.
