### ISSUE TITLE
alidns dns challenge cannot obtaining certificate

### ISSUE THREAD

**Issue by boyce-ywr** [containous/traefik#4052]
when i use alidns dns challenge to obtain certificate, traefik will ouput the following log. It seems that traefik or lego did not correctly read the txt record. After the timeout, the dns challenge was re-initiated, causing the record to be added repeatedly.

```
Unable to obtain ACME certificate for domains \"*.museuminear.com,museuminear.com\" : unable to generate a certificate for the domains [*.museuminear.com museuminear.com]: acme: Error -> One or more domains had a problem:\n[museuminear.com] error presenting token: alicloud: API call failed: SDK.ServerError\nErrorCode: DomainRecordDuplicate\nRecommend: \nRequestId: 1A610C5C-9442-4A65-A4C5-79F51DB97E42\nMessage: The DNS record already exists.
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
