### ISSUE TITLE
HTTP authentication for InfluxDB

### ISSUE THREAD

**Issue by joshuaavalon** [containous/traefik#4072]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

InfluxDB provides [HTTP authentication](https://docs.influxdata.com/influxdb/v1.6/administration/authentication_and_authorization/#authenticate-requests) for its HTTP endpoint

[Traefik does not seems to support it.](https://docs.traefik.io/configuration/metrics/#influxdb)

**Comment by SteveEdson** [comment]
Also having this issue, the configuration doesn't seem to specify any options for a username and password, but it looks like the code might. Tried it, but get the error back from influx:

```
traefik    | time="2018-10-18T19:42:49Z" level=error msg="Error writing to influx: {\"error\":\"unable to parse authentication credentials\"}\n"
traefik    | time="2018-10-18T19:42:49Z" level=info msg="[during WriteTo err {\"error\":\"unable to parse authentication credentials\"}\n]"
```

**Comment by SteveEdson** [comment]
Just to add that I've been able to get this working by changing the host to:

`http://username:password@host.com`

rather than adding the username and password to the config individually.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

Thanks again for your interest in Traefik!

I'm glad to close the issue because I think that the question has been answered (Yes, I'm quite an advanced AI :smile:)

Join our [Slack workspace](https://slack.traefik.io/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by SteveEdson** [comment]
Bad bot.

**Comment by mprasil** [comment]
Can we reopen this? I have the same issue.
