### ISSUE TITLE
Viewing the web dashboard via Kubernetes local proxy

### ISSUE THREAD

**Issue by jimmycuadra** [containous/traefik#409]
When using `kubectl proxy` to access cluster services from your local machine, the Traefik dashboard will be accessed at a URL like http://localhost:8001/api/v1/proxy/namespaces/default/services/traefik. The JavaScript in the dashboard assumes the service is accessible at the root path, and attempts to make requests to, for example, http://localhost:8001/api/providers, which of course returns a 404. Would it be possible for the JS to detect its base path from the initial URL and use that for XHR?

**Comment by jonaz** [comment]
I normally use this to access the web dashboard of specific pod.
```
kubectl port-forward traefik-ingress-controller-0wp62 8080:8080
```

**Comment by pferrot** [comment]
Same problem here, but not with Kubernetes. I have simply configured Traefik to expose its own web UI via a path like /tools/webui...but no luck for the same reason as the one mentioned above.

Is it not a bit embarrassing when your own stuff does not work together ;-)

Other than that, I want to clarify that I really like Traefik!

**Comment by emilevauge** [comment]
> Is it not a bit embarrassing when your own stuff do not work together? ;-)

This issue is only in Kubernetes, due to `kubectl proxy` adding `/api/v1/proxy/namespaces/default/services/traefik` to the path.

If you're using traefik with another backend, you should be able to expose its ui, using a rule like `PathPrefixStrip` which will make our "own stuff work together"...

**Comment by pferrot** [comment]
I used `PathPrefixStrip` but it does not work unfortunately. It will redirect from /tools/traefik/1 (this is the path I need...I have a cluster of Traefiks, hence the number at the end) to /dashboard. And if I force the URL to /tools/traefik/1/dashboard, then some HTML gets loaded, but calls to the API fail (because call are made to /api without my custom path). See screenshot. 

My config looks like this:

```
  [frontends.traefik-traefik___1]
  backend = "traefik-traefik___1"
    [frontends.traefik-traefik___1.routes.test_1]
    rule = "PathPrefixStrip:/tools/traefik/1"
```

![traefik_web](https://cloud.githubusercontent.com/assets/12295384/16115532/d72f1d8a-33c7-11e6-8e72-8b07fd8a8d38.png)

**Comment by emilevauge** [comment]
Hum, indeed :blush:

**Comment by errm** [comment]
I worked around this by exposing the web ui/management api as an ingress.
