### ISSUE TITLE
Traefik should returns 503 when docker backend becomes unhealthy

### ISSUE THREAD

**Issue by cdumarcey** [containous/traefik#4153]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When running Traefik with Docker as a provider on a simple docker host, I found Traefik 
returning 404 when a docker container backend goes unhealthy and frontend is not visible anymore. 

Would it not be better to have Traefik returning 503 for unhealthy container and keep frontend matching rule in that case ?

**Comment by dtomcej** [comment]
Hello @cdumarcey,

If you have docker checking the health of your containers, it will mark them as unhealthy. This tells traefik that the container should not be counted. If you use the traefik health checking labels (traefik.backend.healthcheck.path etc), it will allow this to work the way you want.

Due to the docker provider's stateless nature, we filter out non-viable containers to avoid issues with service discovery.

If you have any further questions, please feel free to reach out to us on slack: traefik.slack.com

Thanks!
