### ISSUE TITLE
Incorrect documentation for kubernetes ingress deployment

### ISSUE THREAD

**Issue by micw** [containous/traefik#4191]
### Do you want to request a *feature* or report a *bug*?

Bug in https://docs.traefik.io/user-guide/kubernetes/ and https://github.com/containous/traefik/blob/master/examples/k8s/traefik-ds.yaml

### Description

The daemonset deployment uses the default updateStrategy (remove manually). In the result it's not possible to update the daemonset unless it's manually deleted before. Any update will cause a new pod to be scheduled, waiting forever that the bound node ports become free.

You should add

      updateStrategy:
        type: RollingUpdate

so if anything is changed on the daemon set, traefik is upgraded one instance after another.

Also the "service" is not required for DS.

**Comment by dtomcej** [comment]
You are correct, the service is not required, but we have it in the event that users want to access traefik from other namespaces.

As for the update strategy, `RollingUpdate` has been the default since K8s 1.5 (https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy) as such, it should be already implemented as the default in users' clusters.

For this reason I will close this ticket.

If you have any further questions or comments, feel free to visit us on slack: traefik.slack.com

Thanks!
