### ISSUE TITLE
Config should use context for better error reporting

### ISSUE THREAD

**Issue by athoune** [containous/traefik#4232]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

When I write something wrong in my config, in the main config file, in some conf.d files, or dynamic config, I would like some context, like source, path and even line number.

I don't know if toml parsing can remember line number, but all configurations have a source.
"One of your config file in your conf.d folder use an unusable certificate" is not a nice error.

Using a context, as first argument in all config functions, something with a source and a path, can be useful when raising errors.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

Issue templates help us help you by providing all necessary information.

Please edit your issue and use the available templates:

- [Feature request](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Feature_request.md)
- [Bug report](https://raw.githubusercontent.com/containous/traefik/master/.github/ISSUE_TEMPLATE/Bug_report.md)

And remember: each time someone ignores the template, a cute little bunny dies.
<details>
<summary>#SaveTheCuteBunny :heart: :rabbit: :heart:</summary>

![southpark - estrella kill rabbit](https://user-images.githubusercontent.com/5674651/27143914-3cea7896-5130-11e7-81f8-02d8ac2da7a7.gif)

![southpark - estrella kill rabbit2](https://user-images.githubusercontent.com/5674651/27143924-49104c72-5130-11e7-82ae-ccedbd5dfa1c.gif)

</details>

**Comment by dduportal** [comment]
Hello @athoune , thank for your interest in the project!

Could you give us more context with a few exemples to help us understand?

Because the TOML parsing will be able to detect a syntax error, but for the semantic, this is another topic.

Without a precise reproductible use case, it is hard to determine a change or a fix :)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
