### ISSUE TITLE
Traefik and FIPS support

### ISSUE THREAD

**Issue by vramanx** [containous/traefik#4256]
Can traefik enable FIPS compliance by compiling and releasing a drop with GO boringcrypto branch?

https://github.com/golang/go/tree/dev.boringcrypto.go1.11

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
