### ISSUE TITLE
Documentation not clear on using Let's Encrypt with Kubernetes

### ISSUE THREAD

**Issue by guidoffm** [containous/traefik#4279]
The documentation does not say if Let's Encrypt is supported with Kubernetes.

There is only a statement "Let's Encrypt certificates cannot be managed in Kubernets Secrets yet."

If Let's Encrypt with k8s is supported there should exist doumentation and usage examples.

**Comment by guidoffm** [comment]
Using the helm chart is useful and helped me to get this running.
However some examples would be useful.

**Comment by JoaoCastroFerreira** [comment]
I'm struggling with the same topic

**Comment by abusaidm** [comment]
I believe the current documentation on `https://docs.traefik.io/v2.0/user-guides/crd-acme/` is out-dated when ran on a new K3 cluster copying and executing the code as instructed.

**Comment by mpl** [comment]
@abusaidm we would need more details about the errors you're encountering to actually help you, but one thing that was not (yet, fixed in https://github.com/containous/traefik/pull/5015) specified in the guide is that with rancher/k3s >= 0.5.0, you need a kubectl >= 0.11. So maybe that was your problem.

**Comment by JoaoCastroFerreira** [comment]
I've put it working . I was  looking at the helm chart and did some reverse engineering.

**Comment by traefiker** [comment]
Closed by #5015.
