### ISSUE TITLE
504 Gateway Timeout not understable

### ISSUE THREAD

**Issue by nicodmf** [containous/traefik#4297]
### Do you want to request a *feature* or report a *bug*?

Bug (near feature)

### What did you do?

When i add a new redirection to container, and i see the logs, traefik doesn't log any error. The only messages are  : 

     time="2018-12-16T14:59:55Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
     time="2018-12-16T15:00:25Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 172.24.0.2:80: i/o timeout"

The reason is so simple : the network configuration.

### What did you expect to see?

A comprehensible message in log to configure traefik or the container.

### What did you see instead?

A uncomprehensible error wich redirect to complexes issues : https://github.com/containous/traefik/issues/2760

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
traefik:alpine:latest
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
#nothing interessant here
```

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
