### ISSUE TITLE
Can the access log file split into more log files ?  When the log is large , it so impress the performance badly!

### ISSUE THREAD

**Issue by panguinbaba** [containous/traefik#4337]
These days , i'm doing performance test, but the log file become so large , it make the system slowly,which i can't bear.So do you have some suggestion?

**Comment by jlevesy** [comment]
Hi @panguinbaba, thanks for your interest in the project.

Traefik does not manage its logs indeed, we recommend to use an external log manager like logrotate in order to deal with that.

Here is a [link](https://stackoverflow.com/questions/49450422/how-to-enable-logrotation-for-traefik) to a stack overflow issue talking about this.
