### ISSUE TITLE
Unclear rate limiting explanation

### ISSUE THREAD

**Issue by ynambiar** [containous/traefik#4549]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you see?

The documentation for Rate Limiting currently reads:

> In the above example, frontend1 is configured to limit requests by the client's ip address.
> An average of 5 requests every 3 seconds is allowed and an average of 100 requests every 10 seconds.
> These can "burst" up to 10 and 200 in each period respectively.

### What did you expect to see?

The second statement, 

> These can "burst" up to 10 and 200 in each period respectively.

is confusing. Does this mean that in any 1s period that the request limit is the "burst" limit? Better explanation of the "period", "average", and "burst" fields would be helpful.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.7.4
```

**Comment by DrEsteban** [comment]
100% agree.  The current explanation is very confusing as to what the difference between "average" and "burst" is, and how each is calculated.

**Comment by tretail** [comment]
As far as I understand the code from vulcand/oxy:

`// newTokenBucket crates a `tokenBucket` instance for the specified `Rate`.
func newTokenBucket(rate *rate, clock timetools.TimeProvider) *tokenBucket {
	return &tokenBucket{
		period:          rate.period,
		timePerToken:    time.Duration(int64(rate.period) / rate.average),
		burst:           rate.burst,
		clock:           clock,
		lastRefresh:     clock.UtcNow(),
		availableTokens: rate.burst,
	}
}`

That means if you have set period=10s, period=100 and burst=200  ; you start a bucket containing 200 tokens. For every request, one token is consumed, and the token will be available again after 10s/100 = 0.1s.
So, if you get more than 20 requests / second, you will reach the burst limit after 20 seconds because you consume more tokens than you are able to refill.
20 seconds because : 400 tokens consumed but also 20s/0.1s=200 tokens refilled.

I hope that is clear enough 👍

**Comment by gouki777** [comment]
The size of the bucket is 200;(burst), 
The average is  control period. (period/average). = httpcode 429 sleeptime.   It's not the average request QPS.
So,Documentation is not precise enough，average != QPS, please correct the document.

**Comment by traefiker** [comment]
Closed by #6277.
