### ISSUE TITLE
Retry does not work for in case of response header timeout

### ISSUE THREAD

**Issue by NicolasFloquet** [containous/traefik#4710]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X] No

### What did you do?
I'm currently using traefik as a Kubernetes ingress, and experimenting the retry feature. 
To this end, I started my traefik pods with following additional parameters:
```
--retry.attempts=5
--forwardingtimeouts.dialtimeout=300ms
--forwardingtimeouts.responseheadertimeout=2s
```

I then tried to test both cases (dialtimeout & responseheadertimeout).

### What did you expect to see?

I expected traefik to retry connection to backend on both dial timeout, and request header timeout.

### What did you see instead?

I see traefik retrying on dial timeout and correctly replying to client if a live backend is found.

In case of request header timeout, 504 error is directly sent to client without any retry

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.9
Codename:     maroilles
Go version:   go1.11.5
Built:        2019-02-11_11:36:32AM
OS/Arch:      linux/arm64

```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

default kubernetes settings

**Comment by mpl** [comment]
Hi,
According to https://docs.traefik.io/configuration/commons/#retry-configuration we only retry in case of a network error, which is why you're only getting retries when dial fails (no server accepted the connection attempt), and not when you're getting a 5XX error (the server accepted the connection, but something went wrong afterwards). So the behaviour you're observing is compliant with the doc.
That being said, it might be legitimate to have a retry mechanism for some kinds of 5XX errors as well, just as you seem to be expecting. If you think so, let us know, and we'll consider marking this issue as a possible enhancement.

**Comment by NicolasFloquet** [comment]
Hi @mpl, and thanks for the quick reply.
I was kinda expecting this answer, and after reading some code, it makes perfect sense.

Yet, as you said, having a similar retry feature for higher level error like 5XXs would be really neat and I would really appreciate if could consider adding it to your enhancement backlog.

Again, thanks a lot!

**Comment by dduportal** [comment]
Hi @NicolasFloquet , thanks a lot for the feedback.

Could you open a separate issue categorized as "feature request" and describe it, so it would be easier for triage?

Thanks in advance!
