### ISSUE TITLE
Feature: a way to enable TLS by default for http

### ISSUE THREAD

**Issue by torarnv** [containous/traefik#4865]
Would be nice if you didn't have to add the tls label to each docker container:

`- "traefik.http.routers.whoami.tls=true"`

But could instead have this in the static config e.g:
```
[http.routers]
  tls = true #default
  
  [http.routers.my-static-route]
     # ...
```

**Comment by dduportal** [comment]
Hi @torarnv, thanks for this feature request and your interest in the project.

Beside being careful to use the issue templates, we are sorry to refuse this request.

The reason is related to the separation of concerns between the ["Static Configuration"](https://docs.traefik.io/v2.0/getting-started/configuration-overview/#the-static-configuration) and the ["Dynamic Configuration"](https://docs.traefik.io/v2.0/getting-started/configuration-overview/#the-dynamic-configuration).

Your request implies to mix static and dynamic configuration, which would have enormous impact in the user experience: it would disable implicitly  the multiplexing of TCP/HTTP over a single entrypoint.

**Comment by torarnv** [comment]
Hi @dduportal, thanks for your reply!

I find the reasoning for closing this a bit strange though. I understand Traefik has a concept of "Static Configuration" and "Dynamic Configuration", but the distinction between the two seem quite arbitrary and inconsistent, and more of an implementation detail. For example:
 
 - There's `Providers.Docker.ExposedByDefault`, but I can override in the dynamic configuration with docker labels, `"traefik.enable=true"`, mixing static and dynamic configuration.
- I can set `TLSOptions.default.ClientCA`, setting "static defaults" within the dynamic configuration.
- I can define a middleware in the file provider, and then reference it from a route in a docker label

As a user I don't really care how it's implemented and how it would "implicitly disable the multiplexing of TCP/HTTP over a single entrypoint". I care about defining the things that don't change _once_, in one place, and leave the rest to be configured per service or route, etc.

Having to duplicate configuration because it falls into the "Dynamic Configuration" options feels like jumping through hoops to satisfy the framework, as opposed to the framework trying to make things easy for me.

This may very well be because my use-case is simple (proxying a handfull of services), and that Traefik is more tailored to larger installations with many heterogenous providers and lots of dynamic configurations, so take that context into account for my reflections  😃
