### ISSUE TITLE
Option to disable mutual ssl per frontend

### ISSUE THREAD

**Issue by mvandewouw** [containous/traefik#4897]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Hi, i would like the option to disable mutual TLS per frontend (with a label)

**Comment by dtomcej** [comment]
Hello @mvandewouw, unfortunately this is not a feature that will be implemented into v1.7, due to it being feature-complete. However, in the upcoming v2, this is not an issue, as TLS is not configured at the entrypoint level, and instead is configured via labels, and thus would be configurable per-router.

For this reason, I will close this issue.

Thanks!
