### ISSUE TITLE
Traefik with multiple subdomains and URLs with a subpath

### ISSUE THREAD

**Issue by cybermcm** [containous/traefik#4904]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X ] No

### What did you do?

Setup: Docker (18.09.6) with one Traefik container, Apache container, multiple other containers (e.g. portainer running behind a subpath)
Apache is configured with

- traefik.frontend.rule=Host:${hostname},www.${hostname}

portainer is configured with

- traefik.frontend.redirect.regex=^(.*)/portainer$$
- traefik.frontend.redirect.replacement=$$1/portainer/
- "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"

Apache container is serving URLs https://hostname and e.g. https://hostname/test
Portainer container served via https://hostname/portainer
Setup works!

Now I want to extend the subdomains for the Apache container like

- traefik.frontend.rule=Host:${hostname},autoconfig.${hostname},autodiscover.${hostname},mta-sts.${hostname},www.${hostname}

Now the following happens:
https://hostname works
https://hostname/test works
https://autodiscover.hostname works

https://hostname/portainer stops working
According to the logs Traefik routes the traffic to the Apache container instead of the Portainer container

This is reproduce able and related to multiple frontend entries. I didn't find an example with more than 2 frontend rules also tried

- traefik.frontend.rule=Host:${hostname},Host:www.${hostname},Host:autoconfig.${hostname}

or

- traefik.frontend.rule=Host:${hostname};Host:www.${hostname};Host:autoconfig.${hostname}

it didn't work...

### What did you expect to see?

All URLs working

### What did you see instead?

URLs with a subpath not working, being redirected to my Apache container instead of the right container (e.g. portainer)

### Output of `traefik version`: (_What version of Traefik are you using?_)

Version:      v1.7.11
Codename:     maroilles
Go version:   go1.11.9
Built:        2019-04-26_08:42:33AM
OS/Arch:      linux/amd64

**Comment by dtomcej** [comment]
Hello @cybermcm,

The issue you are encountering is that you have overlapping rules, and you are not defining any priority to determine order of rule execution.

From the documentation (https://docs.traefik.io/basics/#priorities):

```
By default, routes will be sorted (in descending order) using rules length 
```

So since you have made the host rule _much_ longer, and it matches, it is the first rule.

You can use the priority label to manually force the match of the portainer path first, before the base host match.

Since this is not an issue, but a configuration question, we would like to suggest that you visit us on slack: traefik.slack.com if you have any further questions.

Thanks!

**Comment by cybermcm** [comment]
thx, working now. I'll update my own question at stackoverflow...
