### ISSUE TITLE
whiteList.sourceRange is broken with large amount of ip

### ISSUE THREAD

**Issue by mpomet** [containous/traefik#4907]
### Do you want to request a *feature* or report a *bug*?

Bug

### Case 1 (work) :
**Configuration**
```
labels:
        - "traefik.enable=true"
        - ...
        - "traefik.frontend.whiteList.sourceRange=88.88.88.1/10"
```
**Expected Result**
IP from 88.88.88.1 to 88.88.88.10 are allowed, That works
Other IP results in 403, That works

**Actual Result**
Only ip from 88.88.88.1 to 88.88.88.10 are allowed, That works
Other IP results in 403, That works

### Case 2 (broken) :
**Configuration**
```
labels:
        - "traefik.enable=true"
        - "traefik.frontend.whiteList.sourceRange=88.88.88.1/100"
```
**Expected Result**
Only ip from 88.88.88.1 to 88.88.88.100 are allowed

**Actual Result**
server returns 404, no matter who is doing the request

### Traefik version:

1.7.11 (image: traefik:1.7.11)

**Comment by dtomcej** [comment]
Hello @mpomet,

I think the issue that you are running into is based on the input you are providing.

`88.88.88.1/100` is not a valid subnet in CIDR notation: (https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)

The mask has to be a maximum of 32 bits.

Since the frontend doesn't have a valid whitelist, it is skipped, and not processed, resulting in the 404 you are experiencing. I would try updating your mask to a valid mask, and trying again.

Thanks!
