### ISSUE TITLE
health check for k8s ingress

### ISSUE THREAD

**Issue by jiangrijian** [containous/traefik#5073]
### Do you want to request a *feature* or report a *bug*?

I can't find health check for my k8s ingress, but I can find it in other provider , why? it is very important if you want to check the external service is alive or not.

### What did you expect to see?

If my external service is not alive, traefik will remove this service for my ingress, and if My external service is alive againt, Traefik will add this service automatically.

thanks！

**Comment by dtomcej** [comment]
Hello @jiangrijian, Kubernetes services use endpoints for forwarding traffic.

Endpoints are available when pods pass their readiness and liveliness checks.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

Since Kubernetes has such rich liveliness and readiness checks built into the platform, it does not make sense to implement them _again_ in Traefik.

I hope this helps!

**Comment by jiangrijian** [comment]
Hi @dtomcej, my service is an external service, we have't any pods, just a service and  endpoints.
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services
Is there any other method?
Thank you for your help！

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).
