### ISSUE TITLE
Integration using consul catalog will exit when consul has a leader election

### ISSUE THREAD

**Issue by crumley** [containous/traefik#515]
I am running traefik v1.0.0-rc3 in a docker container and integrating with consul catalog. When my consul cluster experiences load there can be a leader election and for a small amount of time consul will refuse to serve queries. If traefik polls consul during this time an error is returned and traefik exits. The log entry looks like this:

`level=error msg="Failed to fetch details of SERVICE_NAME" error="Unexpected response code: 500 (No cluster leader)"`

Traefik could be more resilient to these problems by retrying with an exponential delay or some similar method to ensure when consul comes back up traefik is ready to obtain the new configuration... ideally serving traffic against the last known configuration.

**Comment by ldez** [comment]
Could you try with the last release? (1.3.0)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
