### ISSUE TITLE
Traefik 2.0: storeconfig missing

### ISSUE THREAD

**Issue by christian667** [containous/traefik#5157]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [X ] No

### What did you do?

Just realised the `storeconfig` argument is not longer valid for Traefik 2.0, is this intented? 
We tried to run traefik in kubernetes (as daemonset) with mutliple instances using etcd as kv-store for acme (and the configuration). Is this not long possible with Traefik 2.0?

### What did you expect to see?

`./traefik storeconfig` should help to bootstrap the configuration within the kv storage.

### What did you see instead?

argument not found

### Output of `traefik version`: (_What version of Traefik are you using?_)

Traefik version is 2.0 beta1

**Comment by dduportal** [comment]
Hi @christian667 , as for today (`v2.0.0-beta1`), the KV provider is not available in Traefik v2.0.

Using a KV like Consul/etcd as Traefik's dynamic configuration provider is indeed expected to be on the final 2.0: please watch the project kanban board for v2.

About the storage of ACME certificates inside a K/V store, you might be interested by [Traefik Enterprise Edition](https://containo.us/traefikee/) which provide the high availability mode for Traefik for all features sensitive to distribution, as ACME, Rate Limiting, etc.
I
 want to bring your attention on the fact that acme in a kv store feature, formerely known as "cluster mode", as always been considered non-production: the documentation of `v1.7` at <https://docs.traefik.io/v1.7/user-guide/cluster/> mention that it's "beta", and also the amount of open issues due to the external KV leader election is worrying: <https://github.com/containous/traefik/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fcluster>.

**Comment by christian667** [comment]
Thank you for your response @dduportal - the cluster mode (running multiple instances of traefik parallel using the same configurations / acme storage) is now part of the EE edition and will not be implemented with the version 2.0 of the CE?

**Comment by dduportal** [comment]
Hi @christian667, you are right, the "running multiple instances of traefik parallel using the same configurations / acme storage" is now part of Enterprise Edition as explained here: <https://docs.containo.us/operating/acme/>.

For Traefik CE 2.0, as explained in [the paragraph "About KV Stores & Distributed Let’s Encrypt" of this blog post from Containous](https://blog.containo.us/back-to-traefik-2-0-the-online-meet-up-4e4b6411fbfa#4b39), it means that our current plan with this is to

* Work on (and improve) Traefik v2.
* Keep supporting v1 for bug fixes.
* Use Traefik EE's architecture for everything that is distributed

I'm closing the issue, as it provides an answer to your initial request.
Feel free to reopen it if you still see a bug on the final 2.0 or if I missed something.

I also invite you to join our [new Community Forum](https://community.containo.us/) if you have any question or feedback that could be valuable to share with the community!

Thanks a lot for your interest!
