### ISSUE TITLE
Error with -consulcatalog and missing load balance method on 1.0.0

### ISSUE THREAD

**Issue by crumley** [containous/traefik#524]
Running the docker image with tag v1.0.0 against a consul catalog results in the following message being sent to the console for every service in consul repeatedly: 

`time="2016-07-13T03:06:13Z" level=warning msg="Error loading load balancer method '<nil>' for backend backend-service-name: Invalid method, using default. Using default wrr."`

Downgrading to v1.0.0-rc3 fixes the issue.

**Comment by errm** [comment]
Looking at the change that caused this to occur it looks to me like we have started logging this message when the load balancer method is not specified and we fall back to the default.

So I don't think anything harmful is happening here apart from excessive logs. Perhaps this should really be info rather than warn, wdyt @emilevauge?

**Comment by emilevauge** [comment]
Indeed, there is no issue here, normal behavior.
But we could move this log to `INFO` to avoid futur misunderstandings.

**Comment by keis** [comment]
IMHO that's still a bit noisy unless it's expected of the backends to always provide this field and in that case I guess the default template for consul_catalog should be updated.

**Comment by crumley** [comment]
The verbosity is killer when you have a lot of services and multiple traefik instances especially when it is quite common for the default to be used in most cases.
