### ISSUE TITLE
Build non static binary with CGO 

### ISSUE THREAD

**Issue by WTFKr0** [containous/traefik#5240]
Hi

We use some tools that inject code in our apps for monitoring/tracing needs
For example, the tool Dynatrace (https://www.dynatrace.com) do that

Such tools inject code at runtime in JVM for example. For binary code, it can inject code in system calls via glibc.

The actual build of traefik (statically linked) is not compatible with these tools, as we need the binary use the OS glibc
Here i recompiled traefik with CGO and some docker image tuning to get my expected result

Does it make sens to you to build also a CGO enabled docker image (linux amd64 for my needs) ? I think others companies (big ones) use such tools to get deep monitoring of their apps.
If yes, i can make a PR quickly on the 1.7 branch and discuss about that

**Comment by WTFKr0** [comment]
For more information on how to build for this use case, see : https://www.dynatrace.com/support/help/technology-support/application-software/go/#application-must-contain-a-symbol-table

**Comment by dduportal** [comment]
Hi @WTFKr0 , thanks a lot for your interest and the description of your use case (please next time: keep the issue template, it make it easier to manage issues).

We are going to close refuse this feature request for the following reason: compiling dynamically Traefik would make it impossible to run inside the `scratch` Docker image, as it would create a strong dependency to underlying `glibc`. It might even have impacts on the `alpine` Docker image as it's using `musl` instead of `glibc`.

Again, we are sorry for the inconvenience. Don't hesitate to open a topic on the Community forum at <http://community.containo.us>, other users might have already been stuck on this use case and we could exchanges solutions, as orchestrating the Dynatrace agent around Traefik's docker container for example.
