### ISSUE TITLE
v2: define rule evaluation order

### ISSUE THREAD

**Issue by Kosta-Github** [containous/traefik#5301]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It should be possible to define a deterministic order for the `rules` evaluation. If you have an incoming request which matches more than one rule, it should be clear/deterministic which rule is chosen for execution.

E.g., if you want to forward one specific URL prefix to one service `A` and all the rest to another service `B`:
* `/pictures/*` -> service `A`
* `/*` -> service `B`

**Comment by dduportal** [comment]
Hi @Kosta-Github , this is possible with v2, but documentation mentions it (as for today), only on the references. It's the property `priority` applied to a router. For example:

- Docker: <https://docs.traefik.io/v2.0/reference/dynamic-configuration/docker/>
- Kubernetes CRD: <https://docs.traefik.io/v2.0/reference/dynamic-configuration/kubernetes-crd/>


=> This issue is labelled as "enhancement" because it might be added on the page <https://docs.traefik.io/v2.0/routing/routers/>.

**Comment by traefiker** [comment]
Closed by #5481.
