### ISSUE TITLE
Please reconsider off-topic policy

### ISSUE THREAD

**Issue by gardner** [containous/traefik#5358]
Hello,
I understand that ticket maintenance can be a huge distraction from "actual work". Please consider that you have an enthusiastic community bubbling around you that is willing to help. Please reconsider your off-topic policy.

I came here after giving 2.0 a whirl. Then I ran into the issue described in https://github.com/containous/traefik/issues/5135 and eventually learned about the removals from https://github.com/containous/traefik/pull/5119

The more important thing that I would like to bring up is that having issues that users run into discussed in a separate forum is a bad idea. 5135 is not an off-topic user-support issue. The error message is bad and can be improved. If you callously dismiss feedback from your userbase then you accept the hazard of growing blind and naive to community sentiment and feedback by increasing the divide between "development" and "user" issues. These "users" are devops, infrastructure engineers, and hackers. They are enthusiastic early adopters. They are your beta testers. By marking every comment as off-topic and locking the issue, you have turned off a feedback mechanism that could have shown you a lot of information. When I see that type of maintainer behavior **I receive a strong message that the project does not want any help or feedback** from RC users. I am happy to continue using 1.7 but I feel like I could help the project more by using pre-release versions.

Additionally, when attempting to sign up at https://community.containo.us/u/account-created
the forums throw an error message: "We cannot detect if your account was created, please ensure you have cookies enabled.". I tried to sign up with email and with GitHub and received the same error.

Thank you,
  Gardner

**Comment by ldez** [comment]
Hello,

Thanks for your feedback.

We try to help everyone in the most efficient way possible for users and for us.

We choose to use GitHub issues only for bugs and features, like many others projects, and we do that since a long time (several years).

We give user support on our recently created [forum](https://community.containo.us/), before we had a Slack.

We encourage constructive contributions and we do our best to sort out all the issues and respond to them.

About #5135, we locked the issue because the last comments were non-constructive.

We can make mistakes, we are human, we do our best and any help is always welcome.

We hope you will continue to contribute and give feedback.

Thank you.
