### ISSUE TITLE
ProxyProtocol not working, DigitalOcean LB unhealthy

### ISSUE THREAD

**Issue by alexanderniebuhr** [containous/traefik#5488]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

Put Traefik on DigitalOcean Droplet behind DigitalOcean LoadBalancer. Enable ProxyProtocol on the Loadbalancer and set flag on Traefik Container `--entryPoints.web.proxyProtocol.insecure=true`

### What did you expect to see?

Healthy Loadbalancer and Client IP Addresses in Logs

### What did you see instead?

Unhealthy Loadbalancer, and just IP Address of Server

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
{"Version":"2.0.0","Codename":"montdor"}
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

Docker Provider

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by alexanderniebuhr** [comment]
Hey folks,

i had more detailed talk with the DO Support team. It looks, that this issue is not on their site.
I also had NGINX installed on the same Droplet, and it does work with the ProxyProtocol. Just the Traefik v2 ProxyProtocol, seems to have an issue.

Could anyone test and confirm this?

Thanks all in advance.

**Comment by zerosym** [comment]
I also have Traefik running on DO, with an auto-provisioned LB feeding into a managed k8s cluster.  Both insecure and trustedIPs modes for proxyProtocol work fine for me, and the load balancer is able to report healthy values for the nodes in the cluster.  It could be that your healthcheck entryPoint / path is somehow misconfigured with Traefik?

**Comment by alexanderniebuhr** [comment]
I have some news on this.
With the official release it seems to be different behavior.

When activating ProxyProtocol on DO LB, the health status drops to unhealthy. After around 2hrs it catches up and gets back to healthy.

This repeats on every change. So always 2hrs wait time. Health check is correct on Traefik Version Api Route

I will keep an eye, and report any update

**Comment by Archanian** [comment]
I came across this issue myself, my nodes would start failing health checks as soon as I enabled the protocol on the LB. Turns out the problem is that if you enable proxy protocol on the LB, your Traefik ping endpoint needs to also have proxy protocol enabled, since I guess the LB applies proxy to its health check calls.

Either expose ping on the web entrypoint, which should already have these settings, or create a dedicated entrypoint for it (which is what I did) ...

```
--ping.entrypoint=ping
--entrypoints.ping.address=:8082
--entrypoints.ping.proxyprotocol
--entrypoints.ping.proxyprotocol.trustedIPs=<CIDR>
```

**Comment by Owersun** [comment]
I have the same issue, but it seems to be not related to ProxyProtocol at all. ProxyProtocol works just fine.
The issue is that DO healthcheck type http is always failing. Regardless where you point it. Neither :80/ work, nor :8080/ping work, while both being health (I checked it by exposing nodes to internet and checking same host:ports as DO loadbalancer connect to, also when checking :80/ I see connections of LB in traefik logs). Seems DO cannot succeed on HTTP healtheck to traefik.
If you change healtcheck type to TCP, so it just open and close the port - it becomes healthy immideately. Well the logs is going to be poisoned with traefik panicking about connections being opened and closed with no data.

**Comment by Archanian** [comment]
That's interesting, I have my DO LB healthcheck type set as HTTP and its working just fine (once I configured my traefik ping entrypoint to accept proxy protocol). Are you running traefik as k8s ingress controller?

**Comment by Owersun** [comment]
I run it on two dedicated nodes and have their host ports directly exposed and targeted by DO LB. pretty much almost "ingress" just a little bit closer to the network and pinned to nodes with fat CPU to run on. Without k8s Service that searches for where the pods run.

PS. Seems to be you are right, when ProxyProtocol is enabled on DO LB, it does healthcheck with proxy protocol as well, so "traefik" entrypoint need to be configured explicitly to accept proxy protocol and then it works. I did that and it seems to be running fine for few minutes already.

**Comment by alexanderniebuhr** [comment]
Hey folks,

thanks for your activity on this.

We also have managed to run healthy checks on DO LB.
However our learnings for our production grade setup are the following:

- DO LB with Traefik, without ProxyProtocol and health check to :8080 -> live health
- DO LB with Traefik, TCP health check -> live health
- Traefik ProxyProtocol works correct and fine -> tested with different LB (custom and service)
- DO LB ProxyProtocol works correct and fine -> tested with HAProxy and Nginx
- DO LB with Traefik, with ProxyProtocol -> it works, but it seems that DO LB needs for us around 2h to get back on track, in the meantime it gets unhealthy peaks (with :80, or :8080 both set to correct settings)

Always to note, we use wildcard's and not dedicated CIDR for our Traefik Settings.

So for us it seems that DO LB and Traefik are a though combination. It works, but if we look at each separate it does work so much smoother.
I don't know if Traefik can do anything about it.

Thanks and keep coding
Alex

**Comment by alexanderniebuhr** [comment]
We have implemented different solution. So I am going to close
