### ISSUE TITLE
Alternative TLS protocols

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [containous/traefik#5582]
It would be cool if you could opt to use LibreSSL, BoringSSL, or (and probably the most interesting from security standpoint) [rustls](https://github.com/ctz/rustls) / [mesalink](https://github.com/mesalock-linux/mesalink).

**Comment by dduportal** [comment]
Hi @Th3Whit3Wolf , could you clarify what do you mean by "opt to use LibreSSL, BoringSSL" exactly? We are not sure to understand what is expected. As a guideline, you might want to use the template proposed for our issues.

As for today, Traefik implements with Golang libraries, and the docker container images uses LibreSSL for OpenSSL implementation (as the default on Alpine Linux).

**Comment by Th3Whit3Wolf** [comment]
My apologies. That's awesome that you guys use LibreSSL, I much prefer it to OpenSSL. What I was saying is it would be nice if you could choose a flag or be able to choose special options at compile time that would allow a user to choose an alternative to the standard LibreSSL. Nginx can use OpenSSL, LibreSSL, or BoringSSL. I would also be interesting in seeing [mesalink](https://github.com/mesalock-linux/mesalink) or [rustls](https://github.com/ctz/rustls) as option since it's core is written in rust and should provide a bulletproof defense against vulnerabilities like heartbleed.

**Comment by dduportal** [comment]
Hi @Th3Whit3Wolf , thanks for your feedback. We are going to close this issue as "declined".

The reason is that Traefik is written in Golang, and use the [TLS Go Library](https://golang.org/pkg/crypto/tls/) for its TLS implementation. Using another implementation means writing a wrapper to another language, and not using the facilities that Golang provides, which would be against the core principles of the project.

Feel free to describe a use case where the current Traefik is problematic if you still consider it as a bug or feature request.
