### ISSUE TITLE
Multiple access log

### ISSUE THREAD

**Issue by rooholam** [containous/traefik#6105]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to have multiple access log file which can be configured with different filters.

This way I can separate each service's access log so that It will be easier to maintain logs.

**Comment by mpl** [comment]
Hi.
We do not think this kind of task is not a part of traefik's responsibilities so we are not going to work on that. Especially since if we accept to work on this kind of feature, we probably would get many other requests in this domain from users having needs different than yours.
We recommend that you leave the task of processing logs to a dedicated log manager software that would get as input the log produced by traefik.
