### ISSUE TITLE
Feature request: dash docs

### ISSUE THREAD

**Issue by securisec** [containous/traefik#6112]
Feature

### Have official Dash docs for traefik?

The traefik docs are awesome, but having the docs for Dash/Zeal would be fantastic.

**Comment by mpl** [comment]
Hello, and thanks for the kind words.
I do not think we'll be spending time on creating whatever is needed for such docs (especially since we don't use them), but we might consider adding them to the project if anyone wants to contribute them. As it seems unlikely to me at the moment, I'm going to close the issue, but feel free to reopen one when/if such a contribution occurs.
