### ISSUE TITLE
cli: check/verify configuration file

### ISSUE THREAD

**Issue by adamdecaf** [containous/traefik#6222]
Feature

### What did you expect to see?

My current [traefik config](https://github.com/moov-io/infra/blob/5f93e13ff37f6a797de84f8ab1a0741f52aa1c39/lib/lb/10-traefik-config.yml#L11) has grown over 600+ lines and I'm increasingly concerned about verifying that config on each pull request issued to it. Being able to verify the configuration parses as YAML and is read properly by the version of traefik it will be deployed against in each PR would be very helpful.

Other projects have a `--verify-configuration` flag or similar which exits to be used in CI.

**Comment by adamdecaf** [comment]
I'll offer to write up a PR if this is approved and we decide on a flag.

**Comment by ldez** [comment]
Hello,

You have mixed, in the `traefik.yml`, the dynamic and the static configuration, we strongly advise against this.

Also I guess that you are using the file provider due the some limitation of the Ingress support in <=v2.1, but in the the next version (v2.2) we added the support of annotation https://github.com/containous/traefik/pull/6160, so you will not have to use the file provider.

If something allow to verify a static configuration file (CLI = static configuration), your file will be mark as invalid, because it's a mix a 2 kind of configuration (dynamic and static).

So we will declined your proposal, thanks anyway.
