### ISSUE TITLE
Feature request: Add InfluxDB support for Traefik Access Log, Traefik Error Log and Tracing

### ISSUE THREAD

**Issue by mr-manuel** [containous/traefik#6256]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

It would be great if I can store the Traefik Access Log (all data which is contained in the JSON version), Traefik Error Log (all data which is contained in the JSON version) and Tracing directly in an InfluxDB for better analyzing.

I know that I can use the Metrics with InfluxDB, but there I'm missing a lot of informations.

**Comment by mpl** [comment]
Hi.
We do not think this kind of task is not a part of traefik's responsibilities so we are not going to work on that. Especially since if we accept to work on this kind of feature, we probably would get many other requests in this domain from users having needs different than yours.
We recommend that you leave the task of processing logs to a dedicated log manager software that would get as input the log produced by traefik.

**Comment by mr-manuel** [comment]
Ok, thank you.
