### ISSUE TITLE
Providers errors metrics

### ISSUE THREAD

**Issue by sylr** [containous/traefik#6258]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

We have a traefik deployment in a kubernetes cluster which numerous teams use as ingress to proxy requests to their services.

It happened that mistakes made in ingresses or ingress routes provoked errors unnoticed for a while until someone took a look at the logs.

Main mistake I could think of are, referencing a secret which is not a TLS certificate, K8S service which does not exists ... etc.

It would be quite useful to have metrics about those alerts so we can do proper alerting via prometheus and avoid having errors poluting the logs for a while.

Regards.

**Comment by mpl** [comment]
Hi.
We do not think this kind of task is not a part of traefik's responsibilities so we are not going to work on that. Especially since if we accept to work on this kind of feature, we probably would get many other requests in this domain from users having needs different than yours.
We recommend that you leave the task of processing logs to a dedicated log manager software that would get as input the log produced by traefik.

**Comment by sylr** [comment]
That's very unfortunate ...

Project like https://github.com/prometheus/prometheus believe otherwise as they expose that kind of metrics:

https://github.com/prometheus/prometheus/blob/a0e8d0d98db87f42dec356240450193a97609a1a/discovery/file/file.go#L142-L146

https://github.com/prometheus/prometheus/blob/f82d55e79f0db8dfdf416d41af04cb34eeceab2c/rules/manager.go#L78-L83
