### ISSUE TITLE
Pass Certificates as Environment Variables

### ISSUE THREAD

**Issue by vaughnmb** [containous/traefik#6419]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?
The ability to pass Certificates as Environment Variables would allow users to run Traefik without having to create a dynamic yml file for certificate handling.  If the Certificate Environment Variables are set,  just write the certificates to a well known location that Traefik can read from.  If the user chooses not to use the Let's Encrypt Challenges, this will allow users to run Traefik without having to create, store, and maintain a customized Traefik docker image.

**Comment by mpl** [comment]
Hi.

We do not support providing elements of the dynamic configuration through environment variables, in part because the number of elements to support would be stupidly long, and increasingly so. And as such, we cannot fairly start supporting one of them (certificates), and not all the others that would surely get requested.
