### ISSUE TITLE
ClientHost is not X-Forwarded-For in Access Logs

### ISSUE THREAD

**Issue by zhengqisong** [containous/traefik#6505]
### Do you want to request a *feature* or report a *bug*?
report a bug

**flow**:   client(10.12.122.2)->SLB(172.16.1.2)->nginx(172.16.1.5)->traefik->pod

**traefik version**: 2.1.6

**Configuration File** 
```
[accessLog]
  filePath = "/path/to/access.log"
  format = "json"
````
**tcpdump**
```
k>.@.Ze.....P..AW=..GET /test.jsp HTTP/1.1
^CConnection: upgrade
Host: mydomain.com
X-Real-IP: 172.16.1.2
X-Forwarded-For: 10.12.122.2, 172.16.1.2
X-Forwarded-Proto: http
RemoteIp: 10.12.122.2
Content-Type: application/json
``` 
**acccesslog**
```
{"ClientAddr":"172.16.1.5:41424","ClientHost":"172.16.1.5","ClientPort":"41424",.......}
```
ClientHost should be 10.12.122.2, 172.16.1.2

### What did you do?
I expected to X-Forwarded-For ip in ClientHost, but the reality is nginx host ip.

**Comment by juliens** [comment]
Thx for your interest in the project!

In fact, this is the expected behavior, the ClientAddr field is the address of the client directly connected to Traefik.
If you really want to have the real ip in the ClientAddr, you need to enable ProxyProtocol in all your proxy chain.

As this is the expected behavior, I will decline this issue.
