### ISSUE TITLE
ability to blacklist/filter certain services from consul

### ISSUE THREAD

**Issue by ripienaar** [containous/traefik#651]
When consul starts it registers itself as a service which then automatically shows up as a service in traefik.

Typically when using something like registrator you'd set SERVICE_IGNORE or similar variables but this particular service is consul creating so even with just consul+traefik and no registrator it's still there.

A generic way to blacklist certain frontends in traefik.toml would be good then there's a generic way to solve this, alternatively the consul integration should just ignore this special service.

![consul service example](http://i.imgur.com/DtPLnKu.png)

**Comment by dtomcej** [comment]
Since the implementation of Provider-specific constraints: (https://docs.traefik.io/configuration/commons/#provider-specific), you can now tag and ignore/vs only process services that match the constraints you set.

Therefore, I will close this ticket.

If you have any further issues, please feel free to open a new ticket.

Thanks!
