### ISSUE TITLE
Marathon provider doesn't seem to fall back to other addresses

### ISSUE THREAD

**Issue by JayH5** [containous/traefik#659]
I've tried to provide multiple Marathon addresses for Traefik, something like:

``` toml
[marathon]
endpoint = "http://controller01:8080,controller02:8080,controller03:8080"
watch = true
...
```

Traefik's logs confirms this config is being loaded:

```shell
time="2016-09-01T10:19:21+01:00" level=info msg="Starting provider *provider.Marathon {\
"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Endpoint\":\"http://cont
roller01:8080,controller02:8080,controller03:8080\",...
```

"`controller01`" is down, however, and cannot be reached. Traefik seems to try this server first as it is the first in the list. The problem is that Traefik never seems to try any of the other (working) servers. It logs something like this:

```shell
time="2016-09-01T10:19:23+01:00" level=error msg="Failed to register for events, Get http://controller01:8080/v2/events: dial tcp 192.168.1.5:8080: getsockopt: connection refused"
time="2016-09-01T10:19:23+01:00" level=error msg="Marathon connection error Get http://controller01:8080/v2/events: dial tcp 192.168.1.5:8080: getsockopt: connection refused, retrying in 841.844912ms"
time="2016-09-01T10:19:24+01:00" level=error msg="Failed to register for events, Get http://controller01:8080/v2/events: dial tcp 192.168.1.5:8080: getsockopt: connection refused"
time="2016-09-01T10:19:24+01:00" level=error msg="Marathon connection error Get http://controller01:8080/v2/events: dial tcp 192.168.1.5:8080: getsockopt: connection refused, retrying in 2.353398941s"...
```

...over and over...

I tried digging in to both Traefik's and [`go-marathon`](https://github.com/gambol99/go-marathon)'s code but didn't have much luck. I'll try look again when I find the time.

**Comment by nnordrum** [comment]
I guess I misunderstood the documentation, because I interpreted that a completely different way.
```
# Marathon server endpoint.
# You can also specify multiple endpoint for Marathon:
# endpoint := "http://10.241.1.71:8080,10.241.1.72:8080,10.241.1.73:8080"
```

I wasn't thinking of it like a zk:// url, but more as "I would like to watch these 3 instances of marathon."

Regardless, I get
```
2016/09/29 23:11:57 Error reading TOML config file /etc/traefik/traefik.toml : Near line 257 (last key parsed 'marathon.endpoint'): Expected key separator '=', but got ':' instead.
```
when I put `endpoint := "doesn't matter what I put here"` in my config file.

Is there a way to connect to two separate marathon instances that anybody is aware of? One of them is going away on in 4 days, so it's not the end of the world, but just wondering now.

**Comment by ariault-blanchard** [comment]
Hi,

I'm meeting the same problem...does anyone found any solution ?

Thx

**Comment by timoreimann** [comment]
@nnordrum go-marathon's URL format is custom: It automatically tries to use one of the other hosts if the current one is failing.

Unfortunately, failover is not working for communication related to the Marathon event bus (which Traefik relies on to receive updates) due to gambol99/go-marathon#212. The log excerpt you posted is exactly the case where Traefik/go-marathon falls short.

The issue you posted afterwards is just that you added a colon where there should be none: The syntax is

`endpoint = <endpoints>`

not

`endpoint := <endpoints>`

Right now, the only workaround is to restart Traefik to make it reconnect to a working Marathon instance.

I will need to get this fixed at some point for myself; however, I cannot promise a time line.
