### ISSUE TITLE
Add non-TLS connection over raw tcp to suppor Minecraft

### ISSUE THREAD

**Issue by Chaoschaot232** [containous/traefik#6630]
Well, I am not a friend from templates so I'll write it simply:

Traefik is a nice tool but it has no support for redirecting raw tcp traffic to MC-Server, which are using domains instead of IP connections.

Normaly, it is done over SRV records, to joine over an url, without the port, but using HostSNI('*') it works with url:port which is also fine but not wanted, because it is no longer limited to that domain it should be limited.

Means, in the TCP part of traefik it is important to implement the non-TLS Host() methode, which is available in e. g. http or add a symple URL() to parse it and redirect it to the correct service.

But for now, it is horrible to setup Minecraft (with/wtihout bungeecord).

Thanks and Cheers
Chaoschaot232

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of communication regulation.

Thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only. My advanced AI has spotted that your issue might be a configuration problem or relates to something that doesn't look like a bug.

To confirm this, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik).

In case I'm wrong (well, that would be embarrassing :sweat_smile:), my developers will re-open the issue and fix me!

In the meantime, you can double check [Traefik's documentation](https://docs.traefik.io/).

**Comment by Chaoschaot232** [comment]
This is a nice bot and a nice response ^^

Well, after all, it isn't a bug, it is a problem within traefik, that it isn't realy possible, to have one static domain for multiply MC servers, because the doc states, that only HostSNI is available for domains.

The problem here is SNI, which is part of TLS and this can't be handled by MC which isn't realy good. So my request is to add a non-SNI-methode, like Host()/URL(), instead of using HostSNI('*'), which isn't that, what I want to use ^^

Would be nice, if this could be looked up :)

**Comment by dtomcej** [comment]
Hello @Chaoschaot232,

I figured I would give you some more insight here.

Minecraft uses a custom TCP protocol, and is not encapsulated in an HTTP request.

TCP connections contain only IP and port information of the source and destination. They do not carry any other information:

https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure

There is no Host, there is no URL, there is no Path.

When you connect to `mc.yourdomain.minecraft.com`, DNS is used to resolve this to an IP, and then a TCP connection is opened to this server.

This is why for TCP, Traefik only allows SNI to be used to route hosts, because the SNI extension does carry the request host as part of the handshake.

Therefore this request isn't a problem with Traefik, the problem is that minecraft does not use a modern communication medium that is easily routable on the web.

You can combine your SRV records to use different ports on Traefik, and configure Traefik to have multiple entrypoints that listen on those ports.

Then you can use those entrypoints to forward to your servers.

Hope this helps.

**Comment by Chaoschaot232** [comment]
Hi @dtomcej ,

thank you for your exntended response. Didn't knew, that MC has it's own TCP protocol.

Well, then this would be the best solution I would say. Do you mind giving me an example how an entrypoint would look like, when the SRV points to the default MC-Port?

Also, modded MC has smth called Dynmap which comes with his own mini webserver, which listens on port 8123 (default).

We used the same config for our gitlab installtion over traefik and it works just fine, but when we try to add any http-nodes/entrypoints for the dynmap, nothing is recognized by traefik. Maybe because MC's log tells every time, that dynmap couldn't create the internal webserver?

If so, then we can easily use the work arround and put the dynmap in a gitlab repro and let a pipeline handle the stuff which wouldn't need dynmap's internal webserver ^^

Have a nice day/nigth :)
