### ISSUE TITLE
about htpasswd pr4831 Password generation modified can add a switch

### ISSUE THREAD

**Issue by yimogit** [containous/traefik#6637]
about htpasswd pr : [traefik/pull/4831](https://github.com/containous/traefik/pull/4831)
Password generation modified

I'm sorry, but I have to say what I'm up to
This change will make it impossible to migrate from the original password and have to be regenerated. I have made a website to generate htpasswd online, but it can't be used now. Can I add switch control?

### Do you want to request a *feature* or report a *bug*?
Feature

**Comment by SuperSandro2000** [comment]
This is just needed for docker-compose files. If you don't escape the ``$`` with a ``$`` docker-compose tries to read a environment variable instead of the password. This is out of traefik's control and changing it will probably break a lot so it will stay like this in the near future.

PS If you are unable to use ``htpasswd`` and ``sed`` on your machine you shouldn't use traefik and who says that you are not feeding a password list with the generated passwords?

**Comment by yimogit** [comment]
thx
