### ISSUE TITLE
CLI command to verify config

### ISSUE THREAD

**Issue by akvadrako** [containous/traefik#6694]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

```
$ traefik verify; echo $?
2020/04/17 13:09:15 command traefik error: field not found, node: lifeCycle
1

$ traefik verify; echo $?
2020/04/17 13:09:15 no configuration errors found
0
```

I use a rather simple setup, i.e. no A/B deployment or staging environment. So when I want to update my base traefik configuration, I stop my old instance then start a new one. I have no way to verify the server will start. It would be nice to have a "verify" or "check" command which loads the config then quits. This will let me know if there are any errors.

This was requested in #6222, but that was declined because the requested was mixing dynamic and static configuration in one file. I'm not doing that.

**Comment by mpl** [comment]
Hi,

Short of actually starting traefik, the only thing a verifier could do is check whether the configuration is all valid syntax, which is something you can already trivially do with a YAML/TOML decoder. So it does not seem worth the trouble.
For a verifier to be actually useful, it would have to actually start traefik. Then again, we don't see the use for that, since there is no added value compared to starting traefik yourself.
