### ISSUE TITLE
Complete Kubernetes Deployment example for AWS?

### ISSUE THREAD

**Issue by oO-Zam** [containous/traefik#673]
I finally got Traefik to work in our Kubernetes cluster, but I'm not entirely sure I go everything right, an since the documentation doesn't really cover much, I want to validate our setup:

Environment: Kubernetes v1.3.6 deployed on AWS with Kops. 3 Masters in HA configuration, nodes and masters in 3 different Availability Zones. 
- Deployment traefik-ingress-lb using v1.0.2 with 2 replica.
- Service for traefik-web-ui pointing to port 80
- *Service for traefik-ingress-lb in LoadBalancer mode, with AWS ELB.
- *DNS entry for lb.k8s.<domain>.com pointing at the AWS ELB.
- *DNS entry for traefik.k8s.<domain>.com CNAME to lb.k8s.<domain>.com
- Ingress for traefik-web-ui mapping  traefik.k8s.<domain>.com to the traefik-web-ui service.
  ... rinse repeat for other services.

steps marked with a \* were not in the example, but seem to be needed for traefik to actually be proxying the external traffic into the cluster.

Also I'm probably going to add an HSA for traefik itself to make sure we scale the proxy based on request. What would be a good measure to use to trigger a scale out or scale back?

Question:
- Is there a better way to set this up?
- Do I need to setup anything else for traefik configuration when it's only accessed via K8s?
- What does traefik uses to health check the services is proxying?

**Comment by errm** [comment]
> Is there a better way to set this up?
This is roughly what I do right now. But it is not optimal.

* If you had some sort of sidekick to register/deregister the elb you could expose traefik with a node port, thus bypassing kube-proxy.
* If you maintain a relatively stable cluster of instances running traefik you could also bypass the ELB and use round robin DNS.

A lot of this depends on what your expectations are around availability vs performance vs connivence.  What you are doing right now is the simplest way to get it working, but may not be as performant.

> Do I need to setup anything else for traefik configuration when it's only accessed via K8s?

No, but on the whole you may not need traefik for internal comunication, kube-proxy + kubedns generally works fine, unless you need to do some complex routing.

> What does traefik uses to health check the services is proxying?

traefik just uses the endpoints that k8s has marked as healthy, this is based on whatever readyness probes you have set on your containers.

**Comment by oO-Zam** [comment]
> If you had some sort of sidekick to register/deregister the elb you could expose traefik with a node port, thus bypassing kube-proxy.

I'm pretty sure that's what the LoadBalancer setting on a K8s service in AWS does. The declaration creates a NodePort internally, then associates an ELB to all the nodes on the cluster, using that port as an entry point. I don't think kube-proxy is involved.

>>Do I need to setup anything else for traefik configuration when it's only accessed via K8s?
>No, but on the whole you may not need traefik for internal comunication, kube-proxy + kubedns generally works fine, unless you need to do some complex routing.

I mean if I have I access to the Traefik configuration file at all, since it seems that everything is done using the Ingress declaration. The regular docs talks about all kinds of options, but I guess none of them really apply in that scenario

**Comment by ekozan** [comment]
I currently try to write a good helm chart for traefik i'll need some helm on AWS

Can I ping you when i'm ready ( on barebone side) ?

**Comment by krancour** [comment]
fwiw, I have just submitted kubernetes/charts#146 containing a Helm chart that uses Traefik as an ingress controller.

**Comment by emilevauge** [comment]
@krancour this is great :)

**Comment by jsravn** [comment]
@oO-Zam node port does use kube-proxy. To avoid kube-proxy you need to use host networking and setup a host port. Then the ELBs can talk directly to traefik. LoadBalancer type in k8s is not ideal at all, it means the ELB will possibly go through any node in your cluster, which then incurs an additional hop to the actual node with traefik. It's also not possible to non-disruptively deploy traefik in this setup (you would need to detach from the ELB beforehand).

**Comment by ldez** [comment]
Maybe resolve by #1602

**Comment by timoreimann** [comment]
@ldez I don't think #1602 does.

We do have a complete Deployment example already. What this issue is really asking for though is a complete example for integrating Traefik on AWS.

I'm on the fence on whether we should try to cover every cloud integration in our documentation. While it'd certainly be helpful, they could change / improve rather quickly so there's a risk they become outdated.

An alternative might be to just point to blog posts and other external instructions along with a warning that we cannot guarantee how up to date they are.

@errm @dtomcej WDYT?

**Comment by kachkaev** [comment]
I'm also curious about how to properly use Traefik in an auto-scalable k8s cluster that is hosted on AWS. I've started a Stackoverflow question on this a couple of weeks ago, but the overall picture in my head is still foggy: https://stackoverflow.com/questions/45279433/make-k8s-services-available-via-ingress-on-an-aws-cluster-created-with-kops/45562238

It'd be great to know if traefik could be used in a HA AWS cluster (i.e. when the number of nodes is varying and when a problem with any of the nodes does not make the services unavailable). A diagram similar [to the one for AWS Ingress Controller](https://github.com/coreos/alb-ingress-controller#design) would be very helpful here. The [helm chart](https://github.com/kubernetes/charts/tree/master/stable/traefik) that is currently available seems to assume an external load balancer in front of the cluster, because traefik's exposed ports do not equal to 80 and 443 – to me that's a bit of a mystery. It's also not very clear where to point the domain names that should be served by traefik inside the AWS k8s cluster.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.
