### ISSUE TITLE
Add new service type: 'ProxyRegex' - Wish to proxy/route (not redirect) wildcards to wildcards.

### ISSUE THREAD

**Issue by doug62** [containous/traefik#6783]
### Do you want to request a *feature* or report a *bug*?
feature

Feature

### What did you expect to see?
Although I can create a router that will REDIRECT/301 *.domain.com to *.anotherdomain.com I need/wish to proxy outside connections to internal endpoints.

I understand that adding this logic to a service might break the design pattern but perhaps the service could simply proxy the target URL as massaged by middle wares - i.e. the service would have no parameters.

My current workarounds include writing a cron to create a file.yml config/map->loadBalancer or perhaps ngix container.

Thanks!

**Comment by mpl** [comment]
Hi,

We're having trouble understanding what you're trying to achieve.
Could you please detail more and/or add a full example of the setup and the behaviour you would like to see?

**Comment by doug62** [comment]
Thanks, I wish to route external hosts/paths to internal hosts/paths, so <wildcardhostname>.outsidedomain.com/<path> would route to <wildcardhostname>.insidedomain.com/<path>.  Essentially a forward proxy but only for specific/fixed routes.  There will be hundreds of <wildcardhostname>s.

**Comment by mpl** [comment]
We still do not understand. Why can't this be achieved with a HostRegex rule?

https://docs.traefik.io/v2.0/routing/routers/#rule

**Comment by doug62** [comment]
Thanks - that would be able to match the incoming route, then run it through some middlewares or send it to a service but it seems that the only service is loadBalancer and that it only proxies to a static host, I would like something like the RegEx/Replacement for that service, or that the service would target a server in a header.  I'm trying to expose hundreds of IOT devices that show up on a VPN to outside world https.

**Comment by mpl** [comment]
Ok, I think we got it.

If we understood you correctly, it seems like you would like to potentially dynamically create a new service depending on some request parameter (say, its intended destination). That is pretty different to the various ways Traefik can create routes, since at the end of the day, the routes (and services) are created by definitions coming from some configuration elements (even if these configuration elements are dynamic ones, e.g. they come from some container label), which is pretty different from what you propose.
 In your proposal, the requests themselves are pretty much the configuration element, and you could potentially end up creating one different router/service for each incoming request, which seems pretty dangerous.
In addition, we think it could pave the road for some serious security exploits, and let attackers create services/routers that you did not anticipate with some clever forging of requests.

However, we think what you're trying to achieve might be doable if you complement traefik with some additional glue of your own that would be in charge of creating the configuration elements that would lead to the eventual creation of the services/routers. You'd get what you want, but you'd stay more in control of what's happening. For example, it seems that the reporter in this issue: https://github.com/containous/traefik/issues/6591 was doing something in a similar vein.

**Comment by doug62** [comment]
I disagree - we would of course filter requests with router rules, re-route to a machine with a regex/replacement, that hose name happens to be a guid, if a call made it to our vpn devices they would still need to be properly formed plus have an auth token, this is safer than forward proxies which are common - please reconsider.  Your design already searches providers like docker/k8... Why not random/variable/regex?
