### ISSUE TITLE
providers.kubernetesingress.ingressendpoint.publishedservice but for Ingress

### ISSUE THREAD

**Issue by ironhalik** [containous/traefik#6803]
### Do you want to request a *feature* or report a *bug*?

Feature

### Some background

I've encountered an issue with AWS ALB deployed in front of Traefik. The setup is as follows:
- alb-ingress-controller deployed
- Traefik deployed with an Ingress object annotated with `kubernetes.io/ingress.class: alb`
  This tells alb-ingress-controller to create an ALB load balancer pointing to Traefik service.
  This ingress has .status.loadblanacer filled with ALB info by alb-ingress-controller. The service the Ingress points to has .status.loadbalancer empty.
- Traefik has `--providers.kubernetesingress.ingressendpoint.publishedservice=<traefik-service>` flag
- App deployed with an Ingress object annotated with `kubernetes.io/ingress.class: traefik`
  The app ingress registers correctly with Traefik and has traffic routed to it. But the app Ingress doesn't have the .status.loadbalancer field updated with ALB info (Traefik couldn't clone it from its own service because it also was empty)

### What did you expect to see?

```
--providers.kubernetesingress.ingressendpoint.publishedingress=<namespace>/<ingress-name>
```
Flag that would behave exactly the same as `--providers.kubernetesingress.ingressendpoint.publishedservice`, but would work with Ingress objects.

### Considerations

This flag could cause some circular logic issues when used incorrectly, but when considered together with the `kubernetes.io/ingress.class` functionality, it seems a perfect fit.

**Comment by dtomcej** [comment]
Hello @ironhalik,

Thank you for your request, but there are a couple of issues with this proposal.

1. By restricting Traefik to watching only `ingress.class: traefik`, and then expecting Traefik to watch for other ingresses outside of that class seems to be an anti-pattern, and is something that we would want to avoid.

2. Having ingress objects updated based on the status of other ingress objects isn't really something that we want to do, partially due to the fact that ingress objects are user facing, and may be updated by a variety of methods (users, operators, etc).

Unfortunately this is not something that we would like to pursue.
