### ISSUE TITLE
K8S: Certificate not removed from acme.json when deleting ingressroute CRD and thus trigger LE rate limit

### ISSUE THREAD

**Issue by derjohn** [containous/traefik#7082]
Hello,
When I create an kind: ingressroute with the CRD and ACME http solver, I get a working Let's Encrypt cert.

When I delete the ingressroute, the route is removed but the cert is still in the cert store (file-based, acme.json). It looks like traefik is trying to renew all expiring cert, no matter if the ingressroute is still there. Im my case there where several hundered certs left, which could not be renewed, but the try itself triggered the _rate limit_ auf 300 orders per 4h. That prevented the valid certs from being renewed.

For those having the same issue:

I removed the certs from the cert with the following jq cmd:
```
jq "del(.le.Certificates[] | select(.domain.main == \"INVALIDDOMAIN"))" /path/to/acme.json
```
and then kill -HUP'ed traefik.

Upon deletion of the kind: ingressroute object in K8S, the CRD should remove the cert
OR
traefik should not try to renew, when there is no route for the cert.

**Comment by mpl** [comment]
We think this is a bad idea because:

1) once the ingressroute disappears, figuring out whether the corresponding cert is not used by _any_ other route (so it can safely be removed) is very far from being trivial.
2) there would be no way to know if the ingressroute went away voluntarily, or as a consequence of a (temporary) service unavailability (in which case we definitely do not want to drop the cert), the latter being way more likely.

However, we do hope at some point to provide an API (which would pretty much be a forwarding to the lego API itself), to let users do things like revoking certificates, if they really want to. Which I believe would address your use-case.

**Comment by derjohn** [comment]
@mpl Thanks for making this clear. And yes, if yo run a host * route, if could by any of the the certs. An API would be very nice but in the meantime: Is there a way to make traefik re-read the acme json file? After changing the acme.json I tried to send kill -HUP with (sadly) comes with a service interruption. If there maybe a different signal available USR1 or so?
