### ISSUE TITLE
Kubernetes TLS through to pod

### ISSUE THREAD

**Issue by stevesloka** [containous/traefik#721]
I am using the kubernetes integration with Traefik. I need to make sure tls is maintained through the entire request. When proxy requests come to my pod which has a self-signed cert I get errors since the source IP (I.e. the service) does not have a proper IP SAN on the cert. 

```
time="2016-10-07T02:49:23Z" level=warning msg="Error forwarding to https://10.2.49.7:443, err: x509: cannot validate certificate for 10.2.49.7 because it doesn't contain any IP SANs" 
```

Is there a way to have the forward use dns instead of the IP? Then I could make my SAN match correctly in the cert.

**Comment by krancour** [comment]
@stevesloka I've worked on things before that require SSL to be terminated at the pod. In a case like that, you don't really want your ingress controller to terminate SSL and then re-initiate it for the next network hop (to the pod) because it adds a lot of overhead.

What's ideal in such a scenario is that whatever components traffic flows through on its way to the pod (this includes the ingress controller) treat those packets as plain TCP traffic. In other words, you don't want your ingress controller doing much more than just netcat'ing to the right upstream service.

I don't want to speak for the Traefik team, but it doesn't seem that this is currently within Traefik's capability. i.e. there's no option for a plain TCP entrypoint, backend, etc. (Although I think those would be great features to add.)

Setting aside the issue of whether Traefik _can_ currently do that or not, a question to ask is: If you'd have your ingress controller not doing much more than netcat'ing, why use it at all (for this particular use case)? After all-- it wouldn't be doing anything more than what every kube-proxy is already doing.

So, assuming you run somewhere like AWS or GKE where the corresponding k8s cloud provider can provision you an ELB or similar, then consider making your app's service one of `type: Loadbalancer`. The result will be plain TCP traffic flowing directly to your pods with no ingress controller as a middle-man. You can terminate SSL at your pods and you're all set, very secure, and haven't introduced a whole bunch of extra latency.

**Comment by stevesloka** [comment]
Thanks @krancour, I can do the ELB route no problem, but don't want the overhead of the elb's in addition to the cost. I have a tool called 'Emmie' (https://github.com/upmc-enterprises/emmie) which deploys feature branches dynamically, and I'm using Ingress resources to give me dynamic url's into my app. 

E.g. branch1.ci.project.com or US1234.ci.project.com

If I can proxy through the plain TCP then that sounds like a good idea and would solve my problem. Alternatively, if I can use k8s dns instead of IP I can write a SAN on the cert and take the overhead.

**Comment by krancour** [comment]
@stevesloka ya... you've cited the best reason I know of for ingress controllers, in general, to get better at L4 routing-- the cost of external load balancers, which can be prohibitive if you have many services.

**Comment by luxas** [comment]
It would be cool if there was an annotation to let traefik trust whatever cert the service exposes to workaround this... or just have querying by DNS name as an option

**Comment by timoreimann** [comment]
[TCP support](https://github.com/containous/traefik/issues/10) (one of Traefik's most popular feature requests) might solve this one too.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered, but feel free to continue the conversation.

**Comment by dimm0** [comment]
Is there still no way to use self-signed certs between traefik and PODs?
I'd like to terminate SSL on traefik, and then use self-signed certs inside the cluster, and give traefik the CA to verify those. But it seems to be using the IPs instead of service name to access the pods, so I can't issue the certs with a correct subject.

**Comment by dimm0** [comment]
Still no way to do actual secure communication to backend? How is everyone solving this?

**Comment by krancour** [comment]
@dimm0 you could do this with a service mesh, but they often don't work well with an ingress controller such as Traefik, so you end up using some alternative gateway mechanism that comes with the mesh, for instance.

**Comment by dimm0** [comment]
I tried using linkerd, and yes it provides TLS between http endpoints, but unfortunately it's not working with host network-bound pods (https://github.com/linkerd/linkerd2/issues/366), which traefik is

Are there any others that will help do this? I looked at istio and couldn't find a solution either

Using other mechanism is also not possible, I have only one 443 port on my nodes, which can't be shared between several ingress controllers

**Comment by krancour** [comment]
Well... like I was saying... I think the meshes I have seen have sort of their own way of doing ingress... so they're sort of mutually exclusive with something like Traefik.
