### ISSUE TITLE
provider config support service/router name with dot

### ISSUE THREAD

**Issue by XGHeaven** [containous/traefik#7283]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Config support dot `.`.
Use docker as example:

```
labels:
  - traefik.http.routers."product.module".rule=Host(`foo.example.com`)
```

### Why need this

Our company use `product`.`module` to name a service. Such as `im.core`/`im.contact`/`im.message`.
We hope traefik can support service/router name includes dot `.`.

**Comment by rtribotte** [comment]
Hello @XGHeaven,

We do not plan to support this feature because it will add too much complexity to our parser, also, the Traefik service do not have to match your service name, you can use either `-`or `_` to name your Traefik services in labels.
Unfortunately, i will close your issue.

Anyway, thank you for your interest in Traefik !
