### ISSUE TITLE
Deploy a Træfɪk cluster

### ISSUE THREAD

**Issue by rokka-n** [containous/traefik#736]
Could somebody help me with understanding what is this cluster and why its needed? I'm so confused about this "master/slave model".

Deploy a Træfɪk cluster
https://docs.traefik.io/user-guide/cluster

Once your Træfɪk configuration is uploaded on your KV store, you can start each Træfɪk instance. A Træfɪk cluster is based on a master/slave model. When starting, Træfɪk will elect a master. If this instance fails, another master will be automatically elected.

**Comment by zhangqx2010** [comment]
I am looking for this too. The doc is too brief to understand.
Does this master/slave model hold one floating IP together?
How do the master/slave work if master failed?

**Comment by dcrystalj** [comment]
I think all you need is to set mode=global and set consul.endpoint to all consul instances but real bummer is that right now you cannot make consul fault tolerant (https://github.com/hashicorp/consul/issues/993#issuecomment-286792530) which means you cannot make traefik fault tolerant neither.

**Comment by ascora** [comment]
You can also use Docker Swarm Mode and use
--mode global
which will then launch a traefik instance on each node and works perfectly fine as long as there is at least one working node in the cluster.

**Comment by dcrystalj** [comment]
Yes you can use --mode global and I have set --docker.watch as well, but I think trafik is not hot reloading settings if its not connected to consul. I cannot access apps which were killed together with dead node and then restored on another node.

**Comment by zhangqx2010** [comment]
Good to see your replies. I deployed traefik in linux not in docker and already used global mode config to store kv in consul. 
I just want to know if one traefik node failed while consul works fine, is it possible to finish fault tolerant on traefik layer.(like haproxy's floating ip for HA feature)
Or we can just put a loadbalancer like F5 to handle front end request deliver?

**Comment by zhangqx2010** [comment]
And today I found that to some extent I may misunderstand the design purpose of traefik. So Just leave this comment alone.

> zhangqx2010 commented an hour ago
Good to see your replies. I deployed traefik in linux not in docker and already used global mode config to store kv in consul.
I just want to know if one traefik node failed while consul works fine, is it possible to finish fault tolerant on traefik layer.(like haproxy's floating ip for HA feature)
Or we can just put a loadbalancer like F5 to handle front end request deliver?

Since consul does not support multiple endpoints. We can work around by set up local consul agent for traefik backend kv store.

**Comment by ajardan** [comment]
I would also be interested to understand what is this cluster mode for ? Is that an attempt to make the health dashboard unified while running more than 1 instance of traefik ?

**Comment by dottgonzo** [comment]
i'm new on swarm mode, and i'm just trying to use some cheap vm on internet to test all. For now my testing cluster is made by a docker manager node + 2 slave nodes. On each one is installed docker of course, and glusterfs. I've setup gluster to be able to syncronize the data between the nodes, then i start to deploy all the services with traefik+acme WITHOUT a kv store and everythings seems working really good. Then i plan to add anothe manager and want eliminate the issue that if traefik goes down, services stop to be available from outside, because traefik became crucial on this scenario. So start to read about consul and everything, but as read here, add redundant traefik+consul, is not stable, so my question is:

why i need to use consul or other kv store if traefik run as cluster, when i can replicate traefik (only on other replicated docker manager, i thing that replicate traefik on nodes is unuseful) by using a shared acme+toeml file?

**Comment by ldez** [comment]
@dottgonzo Thanks for your interest in Traefik !

The issue tracker is for reporting bugs and feature requests only.
For end-user related support questions, refer to one of the following:

- [Stack Overflow](https://stackoverflow.com/questions/tagged/traefik) using the "traefik" tag
- the [Traefik community Slack channel](https://traefik.herokuapp.com)

**Comment by dottgonzo** [comment]
@ldez 
my post will refear to the problem of "Deploy a Træfɪk cluster", sorry if supposing to replicate the file instead of deploy the kv store seems stupid...

**Comment by SvenAbels** [comment]
@dottgonzo You don't need consul in this case. We got the same scenario that you described and if you deploy traefik with the docker provider as a global service then all instances will retrieve the configuration and there is no need for consul or any other shared KV for traefik.

**Comment by Overbryd** [comment]
I am also still puzzled by this cluster mode.

So what I want is simple: Multiple traefik instances running in my Kubernetes cluster. They should all share one configuration and one acme file.

Is this what cluster mode is for?
Is it covered by running traefik in Kubernetes mode?
Or do I need to deploy a separate KV-store next to traefik?

**Comment by ajardan** [comment]
@Overbryd you need the key-value store to use ACME on multiple traefik instances.

**Comment by traefiker** [comment]
Closed by #2589.
