### ISSUE TITLE
What's the max number of concurrent connections for traefik?

### ISSUE THREAD

**Issue by sunnysideocean** [containous/traefik#739]
When using Apache or nginx or even haproxy, I always configures the max number of concurrent connections (e.g. via worker_connections for nginx). Can't this be done in traefik as well?

What is the default one for traefik?

**Comment by sunnysideocean** [comment]
Is there noone who can help me here? Or is there no limitation in parallel connections in traefik (except for CPU restrictions)?

**Comment by Yggdrasil** [comment]
I don't think there is a fixed limit. You could ask on http://traefik.slack.com/ to be sure.

Make sure to set the max_open_files ulimit for Traefik to a sufficiently high number, since each concurrent open connection uses a file and not all clients correctly close connections either. Some OS's like Ubuntu have a quite low default of 2048 and you'll run into Too Many Open Files errors on heavy traffic. I increased max_open_files to 16384 on a reasonably busy webserver, which was sufficient for us.

**Comment by emilevauge** [comment]
@Yggdrasil is right, there is no limit for now. Do you need it ?

**Comment by sunnysideocean** [comment]
Perfect. :-) I don't need a Limit but I was more concerned that there may be a limit, which I need to increse manually without knowing it.

**Comment by emilevauge** [comment]
Great! Closing this one then ;)
