### ISSUE TITLE
Dynamic configuration from file is ignored if static configuration is in k/v store

### ISSUE THREAD

**Issue by alvaroaleman** [containous/traefik#803]
If a ``traefik.toml`` file does not contain the static part, it's dynamic part (below ``[file]``) is completely ignored.

**Comment by traefiker** [comment]
I'll close the issue due to inactivity but feel free to re-open if needed.

**Comment by nmengin** [comment]
Hello @alvaroaleman.

Since the version 1.5, it's possible to store both static and dynamic configuration into a KV store as you can see [here](https://github.com/containous/traefik/pull/2419).

Do you think it can solve your use case?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).
