### ISSUE TITLE
Question: What are URL variables in front end rules used for?

### ISSUE THREAD

**Issue by hartzell** [containous/traefik#886]
The [front ends](https://docs.traefik.io/basics/#frontends) section of the basic docs states that URL variables can be defined in rules, e.g.:

```
Path: /products/, /articles/{category}/{id:[0-9]+}
```

As far as I can tell, these variables are not used for anything downstream.

Have I missed something?

**Comment by Regner** [comment]
It isn't about adding variables that are passed downstream it is about putting RegEx into the path that you can easily reason about... I think.

Imagine you had a route something like `/products/{id: [0-9]+}/details/` and another route `/products/{id: [0-9]+}/related/` and that each of those went to different backends. You need to be able to tell the Traefik to route to specific backend services with a variable in the path.

I don't know the original reasoning for allowing you to name the RegEx groups but I know I use it so that it is easier to read the configs.

`/articles/{}/{[0-9]+}/details/` and `/articles/{}/{[0-9]+}/related/` are both far harder to read and understand when they don't have names, especially when you start getting lots of them.

**Comment by hartzell** [comment]
Thanks for following up!

Having patterns/regular-expressions in the paths being matched makes sense.

I'm still mystified by this bit from the example: `/articles/{category}/{id:[0-9]+}`.  I *think* that `{category}` is actually shorthand for `{category:.+}`, which in turn is actually a verbose way of writing `{.+}`, since the labels don't seem to ever be used for anything.

I disagree about your final point (particularly if you actually put a `.+` in the second part of the paths in your example).  They're just patterns to be matched.  Naming them only *adds* to the complexity ("in my opinion..." :smile:), the additional complexity is worth putting up with if you're going to use the names downstream, otherwise it's only overhead.

I thought that they might be useable as part of the path component of the backend *url*, but based on experimentation only the scheme, host, and ports part of the backend url are used.  These two seem to function identically:

```
http://192.168.99.100:8080
http://192.168.99.100:8080/bar
```

I thought perhaps one could do:

http://192.168.99.100:8080/bar

**Comment by ThinkBriK** [comment]
Hi !

Have a look to underlying router (ie. gorilla/mux) : [http://www.gorillatoolkit.org/pkg/mux#Route.Path](http://www.gorillatoolkit.org/pkg/mux#Route.Path)

**Comment by hartzell** [comment]
@ThinkBriK -- So the gorilla/mux docs say this:

> They can be retrieved calling mux.Vars(request).

Are those matches used for anything in traefik?

g.

**Comment by ThinkBriK** [comment]
As far as I know : no...
But at least it's easier to understant the "why"  (underlying component notation).

**Comment by hartzell** [comment]
Got it.  Sounds reasonable.

**Comment by timoreimann** [comment]
@hartzell:

>I _think_ that `{category}` is actually shorthand for `{category:.+}`, which in turn is actually a verbose way of writing `{.+}`, since the labels don't seem to ever be used for anything.

I don't think it's a short-hand for `{.+}`: According to the [Gorilla documentation](http://www.gorillatoolkit.org/pkg/mux), the default is to match until the next slash. Quoting (**emphasis** by me):

>Paths can have variables. They are defined using the format {name} or {name:pattern}. **If a regular expression pattern is not defined, the matched variable will be anything until the next slash**.

So I guess you could say it's a short-hand for `{category:[^/]*}`.

The naming seems to be needed only for the sake of being able to define a regular expression.
