### ISSUE TITLE
Frontends/Backends from multiple providers - is this supported?

### ISSUE THREAD

**Issue by miracle2k** [containous/traefik#966]
- I'd like to have a backend defined in my .toml file.
- I would then like to add frontends via etcd.

I got the idea that this is supported, based on the CLI design and the fact that in the WebUI, it shows the routes from both; but in practice, I couldn't get it to work. Should it work, or do I not need to investigate?

**Comment by cyrilgdn** [comment]
Interested in this issue as well, I tried to use both consul and consul_catalog but can't create a consul frontend which use a consul_catalog backend.

**Comment by srgrn** [comment]
I also seem to have a similar problem.
according to the image on the site it seems like docker backend is connected to the file frontend, but i can't seem to do this.

**Comment by jmahowald** [comment]
While I agree that it would be nice to be a top level feature, I do think you can do this on your own with confd.  

https://github.com/rawmind0/rancher-traefik

Uses confd to scan rancher metadata and then generates the toml.  

This setting:
https://github.com/rawmind0/rancher-traefik/blob/master/root/opt/tools/confd/etc/conf.d/rules.toml.toml

Get's confd to listen to changes and updates the (admittedly a bit hard to read) template

https://github.com/rawmind0/rancher-traefik/blob/master/root/opt/tools/confd/etc/templates/rules.toml.tmpl

**Comment by denysvitali** [comment]
Same issue here with `consul_catalog` (as a backend) and `file` (as a frontend). Is it possible to connect the two so that I can create a frontend as a `[frontends]` entry, and keep the provided backend from `consul_catalog`?

**Comment by kajmagnus** [comment]
I have a similar use case:  I'd like to add backends dynamically via the Docker provider.  And I'm going to have a list of frontend `Host: ....` rules, in a .toml file auto generatedby the app server(s), which I'd like Traefik to watch and auto reload.  (No consul or etcd in my case; that'd be overkill :- ))

So, dynamic backends via the Docker provider. And dynamic frontends via the File provider.

(For now I'm just hardcoding the backend server in a file, for the File provider, since for the moment there's just one.)
