### ISSUE TITLE
gzip compression per (docker) endpoint?

### ISSUE THREAD

**Issue by MihaMarkic** [containous/traefik#981]
If I understand correctly, compression is currently supported only per endpoint - all or nothing.
Is is possible to have it mixed? Some frontends require traefik compression, some do it on their own.

**Comment by MihaMarkic** [comment]
Or at least not compress already compressed content.

**Comment by benfavre** [comment]
I'm facing this issue.
Would have liked to be either :
- be able to disable compression on one of my docker services with a label
- be able to explicitely turn compression on on every service that needs it

**Comment by jprobinson** [comment]
Hi, really sorry for the delay on responding here...

I'd prefer this library to follow the principle of least surprise and simply compress any/all requests that flow through it. 

If you're running a mix of compressed _and_ non-compressed endpoints on the same server, I would suggest using two separate middleware stacks and wrapping the endpoints accordingly. For a good example of this practice, take a look at how Go Kit composes endpoints and middleware in it's examples: https://github.com/go-kit/kit/tree/master/examples

As for Traefik, I would suggest updating the service to move the `compress` configuration to individual back end services for a finer control.

**Comment by ldez** [comment]
Closed in favor of #1060

**Comment by djeeg** [comment]
With the new 1.5 release, I am trying to convert all my TOML entryPoints to pure docker compose label configuration, however it looks like I cant fully switch over yet, because a compress option doesnt seem to be configurable with docker labels. 

Where you mention 1060 as a solution, that seems to be double compression related, I cant see any hints of a way to enable compression via label. Nor do I see the labels definitions on the docs page https://docs.traefik.io/configuration/backends/docker/. Have I missed something, or can this issue be re-opened?

**Comment by ldez** [comment]
@djeeg The compress option is a part of the static configuration.
Labels are available only for frontend or backend configuration (dynamic configuration).

Entrypoint (as a part of the static configuration) cannot be defined by labels.

But you can use CLI entrypoint configuration in your docker compose:

```shell
traefik --entryPoints='Name:http Address::80 Compress:true'
```

**Comment by djeeg** [comment]
Hey Idez, sure that's where I currently have my compress setting atm, in the static config

Was just checking if other entryPoint settings (eg compress) had also moved into the dynamic configuration options (like redirect had for 1.5). I guess it has not and there are no plans to do so. (I dont mind either way, i just thought I had missed a bit of documentation) 

Thanks for the release!

**Comment by kachkaev** [comment]
Enabling compression for just some of the microservices that are sharing an endpoint would be useful indeed. I have a typical website with a frontend (React / Next.js / Express) and an API (GraphQL / Apollo Server / Express). Both are sharing the same HTTPs endpoint. Compressing everything for the frontend is not so reasonable, because it returns quite a few images that already compressed (double-compression of JPEGs simply drains users' battery with added gain). So until https://github.com/containous/traefik/issues/2124 is possible, the best strategy for the frontend would be to compress CSS, HTML and JS only by itself. The GraphQL server on the other hand is an endpoint that always returns text. The compression can be done by express as well, however, this is more expensive than to let traefik do this. It'd be great to just assign some label to the docker container and not bother with `app.use(compression());` on the JavaScript side.

The problem of being able to define compression strategy just at the entry point is that it's either all or nothing. One instance of traefik can proxy quite a few microservices with various needs and limitations. So having a higher granularity for the compression strategy would be great indeed!
